/* ============================================================
   ANDIJON VAGON DEPOSI — TELEJKA TA'MIRLASH SEXI
   MA'LUMOTLAR BAZASI
   ============================================================ */

/* 1) XODIMLAR — sex shtati */
const XODIMLAR = [
  {"ism":"Avazbek Axmedov","lavozim":"Sex ustasi","toifa":"7-toifa"},
  {"ism":"Hayrullo Raximov","lavozim":"Sex ustasi","toifa":"7-toifa"},
  {"ism":"Kamola Umarova","lavozim":"Brigadir","toifa":"6-toifa"},
  {"ism":"Jasur Inobiddinov","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Abdulxamid Xasanov","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Roziqov Xotamjon","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Qobilov Marufjon","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Anvar Axmedov","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Alimqulov Qaxramon","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Xamdamov Muhammadyusuf","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Qo'ziyev Ar-Rauf","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Maxamadov Asadbek","lavozim":"Chilangar","toifa":"4-toifa"},
  {"ism":"Qo'ziboev Shuxrat","lavozim":"Elektrpayvandchi","toifa":"4-toifa"},
  {"ism":"Nishonov NEmatillo","lavozim":"Elektrpayvandchi","toifa":"5-toifa"},
  {"ism":"Omonov Qodirjon","lavozim":"Elektrgazpayvandchi","toifa":"4-toifa"},
  {"ism":"Xodjiboyev Biloliddin","lavozim":"Elektrgazpayvandchi","toifa":"4-toifa"},
  {"ism":"Olimjonov Ulug'bek","lavozim":"Nuqson topuvchi","toifa":"4-toifa"},
  {"ism":"Matxoliqov Nurullo","lavozim":"Nuqson topuvchi","toifa":"4-toifa"},
];

/* 2) KUTUBXONA — elektron kitoblar */
const KITOBLAR = [
  {"nom":"РД 32 ЦВ 050-2020 — shablonlar bilan o'lchash tartibi (qo'llanma)","muallif":"","format":"PDF · 7,4 MB · 80 bet","mavzu":"shablonlar","havola":"kitoblar/RD-32-CV-050-2020-shablonlar-qollanma.pdf"},
  {"nom":"РД 32 ЦВ 050-2020 (с 01.01.2025)","muallif":"","format":"PDF","mavzu":"normativ hujjat","havola":"kitoblar/РД 32 ЦВ 050-2020 (с 01.01.2025).PDF"},
  {"nom":"РД 32 ЦВ 052-2009 (с 01.07.2026 г)","muallif":"","format":"PDF","mavzu":"normativ hujjat","havola":"kitoblar/РД 32 ЦВ 052-2009 (с 01.07.2026 г).pdf"},
  {"nom":"РД 32 ЦВ 067-2022 (с 01.01.2025г)","muallif":"","format":"PDF","mavzu":"normativ hujjat","havola":"kitoblar/РД 32 ЦВ 067-2022 (с 01.01.2025г).pdf"},
  {"nom":"РД 32 ЦВ 082-2021 (с 01.01.2026 г)","muallif":"","format":"PDF","mavzu":"normativ hujjat","havola":"kitoblar/РД 32 ЦВ 082-2021 (с 01.01.2026 г).pdf"},
  {"nom":"Руководства ДР Пасс вагон","muallif":"","format":"PDF","mavzu":"normativ hujjat","havola":"kitoblar/Руководства ДР Пасс вагон (2).pdf"},
  {"nom":"Сварка_и_наплавка_корпуса_буксы_Технологическая_инструкция_ТИ_05","muallif":"","format":"PDF","mavzu":"normativ hujjat","havola":"kitoblar/Сварка_и_наплавка_корпуса_буксы_Технологическая_инструкция_ТИ_05.pdf"},
];

/* 3) DARSLIKLAR — o'quv materiallari
      1-10:  РД 32 ЦВ 050-2020 (o'lchash metodikasi)
      11-17: РД 32 ЦВ 052-2009 (umumiy ta'mir rahbariyati)
      18-19: ПР НК В.3 (buzmasdan nazorat qoidalari)
      Har bir darslik darsliklar/ papkasidagi alohida HTML sahifada ochiladi. */
const DARSLIKLAR = [
  {"nom": "Yuk vagon aravachasi va uni ta'mirlash tizimi", "davomiyligi": "30 daq", "daraja": "Boshlang'ich", "havola": "darsliklar/01-yuk-vagon-aravachasi-va-uni-tamirlash-tizimi.html"},
  {"nom": "РД 32 ЦВ 050-2020 metodikasi bilan tanishuv", "davomiyligi": "25 daq", "daraja": "Boshlang'ich", "havola": "darsliklar/02-rd-32-cv-050-2020-metodikasi.html"},
  {"nom": "O'lchash shartlari va o'lchov vositalari", "davomiyligi": "35 daq", "daraja": "Boshlang'ich", "havola": "darsliklar/03-olchash-shartlari-va-olchov-vositalari.html"},
  {"nom": "Nadressor balkasi: prizma qiya yuzalari burchagini nazorat qilish", "davomiyligi": "40 daq", "daraja": "O'rta", "havola": "darsliklar/04-nadressor-balkasi-prizma-qiya-yuzalari-burchag.html"},
  {"nom": "Nadressor balkasi: «З» tayanch yuza uzunligi", "davomiyligi": "40 daq", "daraja": "O'rta", "havola": "darsliklar/05-nadressor-balkasi-z-tayanch-yuza-uzunligi.html"},
  {"nom": "Nadressor balkasi: qalinlik, burtlar, skolzun va qattiqlik", "davomiyligi": "35 daq", "daraja": "O'rta", "havola": "darsliklar/06-nadressor-balkasi-qalinlik-burtlar-skolzun-va.html"},
  {"nom": "Yon rama: buksa proyomi va bazaviy o'lcham «М»", "davomiyligi": "40 daq", "daraja": "O'rta", "havola": "darsliklar/07-yon-rama-buksa-proyomi-va-bazaviy-olcham-m.html"},
  {"nom": "Yon rama: friksion plankalar", "davomiyligi": "45 daq", "daraja": "Yuqori", "havola": "darsliklar/08-yon-rama-friksion-plankalar.html"},
  {"nom": "Friksion pona va buksa zazorlari", "davomiyligi": "45 daq", "daraja": "Yuqori", "havola": "darsliklar/09-friksion-pona-va-buksa-zazorlari.html"},
  {"nom": "Ressor komplekti va friksion ponalar holati", "davomiyligi": "40 daq", "daraja": "O'rta", "havola": "darsliklar/10-ressor-komplekti-va-friksion-ponalar-holati.html"},
  {"nom": "Aravacha modellari va texnik xarakteristikalari", "davomiyligi": "35 daq", "daraja": "Boshlang'ich", "havola": "darsliklar/11-aravacha-modellari-va-texnik-xarakteristikalari.html"},
  {"nom": "Aravachani qismlarga ajratish (razborka)", "davomiyligi": "35 daq", "daraja": "Boshlang'ich", "havola": "darsliklar/12-aravachani-qismlarga-ajratish.html"},
  {"nom": "Dеfektatsiya — brak mezonlari", "davomiyligi": "45 daq", "daraja": "O'rta", "havola": "darsliklar/13-defektatsiya-brak-mezonlari.html"},
  {"nom": "Yon ramalarni ta'mirlash", "davomiyligi": "50 daq", "daraja": "Yuqori", "havola": "darsliklar/14-yon-ramalarni-tamirlash.html"},
  {"nom": "Nadressor balkasini ta'mirlash", "davomiyligi": "50 daq", "daraja": "Yuqori", "havola": "darsliklar/15-nadressor-balkasini-tamirlash.html"},
  {"nom": "Ta'mirdan keyin aravachani yig'ish", "davomiyligi": "45 daq", "daraja": "O'rta", "havola": "darsliklar/16-tamirdan-keyin-aravachani-yigish.html"},
  {"nom": "Ta'mirdan chiqarishdagi yakuniy nazorat", "davomiyligi": "50 daq", "daraja": "Yuqori", "havola": "darsliklar/17-tamirdan-chiqarishdagi-yakuniy-nazorat.html"},
  {"nom": "Buzmasdan nazorat (НК) — asoslar va zonalar", "davomiyligi": "50 daq", "daraja": "O'rta", "havola": "darsliklar/18-buzmasdan-nazorat-asoslar-va-zonalar.html"},
  {"nom": "МПК va ВТК o'tkazish, natijani baholash", "davomiyligi": "50 daq", "daraja": "Yuqori", "havola": "darsliklar/19-mpk-va-vtk-otkazish-natijani-baholash.html"},
];

/* 5) SHABLONLAR — o'lchov shablonlari va o'lchash tartibi
      Manba: РД 32 ЦВ 050-2020 (2025-yil 1-yanvardan amaldagi tahrir) */
const SHABLONLAR = [
  {"nom": "Shablon НП Т914.05.000 — umumiy ko'rinishi", "rasm": "rasmlar/01-shablon-np-umumiy.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.1–5.1.2 · ТУ 32 ЦВ 2021-95\nTuzilishi: 1 — polzunok, 2 — oyoqchalar, 3 — nakladka, 4 — dvijok. Bazaviy o'lcham — 175,5 mm, tarmoqlari 45° ostida, oyoqchalar tayanch yuzadan 10 mm balandlikni beradi.\nVazifasi: nadressor balkasi prizmasi qiya yuzalarining 45° burchagi dopuskini va tayanch yuza uzunligi «З» ni nazorat qilish."},
  {"nom": "Shablon НП — nadressor balkasidagi ish holati", "rasm": "rasmlar/02-shablon-np-ish-holati.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.1\nShablon oyoqchalari (poz. 2) bilan prizmaning tayanch yuzasiga o'rnatiladi va nakladka (poz. 3) bilan balkaning qiya yuzasiga zich bosiladi.\nO'lchash IKKITA kesimda — qiya yuzalarning yo'naltiruvchi burtlari chetidan 15…30 mm masofada bajariladi."},
  {"nom": "45° burchak dopuskini o'lchash sxemasi", "rasm": "rasmlar/03-45-burchak-dopuski.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.1\nTartib: 1) polzunokni eng quyi holatga tushiring; 2) dvijokni qiya yuzaga tekkuncha suring — «C1past»; 3) polzunokni eng yuqori holatga ko'taring — «C1yuqori»; 4) K1 = |C1past − C1yuqori| < 3 mm; 5) shu tartib ikkinchi qiya yuzada takrorlanadi — K2 < 3 mm.\nIshoralar: dvijok «0» dan o'ngda — «−», chapda — «+».\nMisol: C1past = −4 mm, C1yuqori = −2 mm → K1 = 2 mm < 3 mm — me'yorda.\nMe'yor: pastdagi umumiy tirqish 6,0 mm dan ko'p emas."},
  {"nom": "«З» — tayanch yuza uzunligini aniqlash", "rasm": "rasmlar/04-z-tayanch-yuza-uzunligi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.2\nDvijok qarama-qarshi qiya yuzadagi eng katta yeyilish joyiga tekkuncha suriladi va «K» ko'rsatkichi ishorasi bilan olinadi.\nFormula: «З» = 175,5 + (1,41 × «K»). Misol: K = −4 → З = 169,9 ≈ 170 mm.\nK:  +2,5 / +2 / +1 / 0 / −1 / −2 / −3 / −4 / −5 / −6 / −7\nЗ:   179 / 178 / 177 / 175,5 / 174 / 173 / 171 / 170 / 168 / 167 / 166\nMe'yor: 175±1 mm; 175(+3/−1) — 18-1750, 18-7055; 175(+4/−1) — 18-9801, 18-100. Depo ta'miri — «З» ≥ 166 mm (K ≥ −7); kapital ta'mir — 174 < «З» < 179 mm."},
  {"nom": "Ultratovush nazorati — o'lchash zonalari sxemasi", "rasm": "rasmlar/05-ultratovush-zonalar.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.3\nNadressor balkasi qiya yuzalarining qolgan qalinligi 1, 2, 3, 4-zonalarda ultratovush qalinlik o'lchagich bilan o'lchanadi.\nYuza tozalanadi, kontakt suyuqligining ingichka qatlami suriladi, ПЭП exo-signal ishonchli ajraladigan qilib o'rnatiladi.\nAgar 1-zonada natija h_min dan kichik chiqsa — qo'shni ikkita nuqtada qo'shimcha o'lchanadi va uchtasining o'rta arifmetigi olinadi.\nMe'yor: qolgan qalinlik 7,0 mm dan kam emas."},
  {"nom": "Impulsli defektoskop ekrani — strob sozlash", "rasm": "rasmlar/06-defektoskop-ekrani.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.3\nDefektoskop kuchaytirishi shunday sozlanadiki, qarama-qarshi devordan kelgan exo-signal amplitudasi strobning bo'sag'a darajasidan 1–2 katak yuqori tursin.\nBarqaror natija olingandan so'ng chuqurlik o'lchagich ko'rsatkichi h yozib olinadi."},
  {"nom": "Shablon Т914.007 — burtlar orasidagi «e» masofasi", "rasm": "rasmlar/07-shablon-t914-007-e.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.4 · ТУ 32 ЦВ 2023-2000\nFriksion pona uchun cheklovchi burtlar orasidagi «e» masofasi shablon Т914.007 bilan gorizontal tekislikda, burtlarning BUTUN yuzasi bo'ylab nazorat qilinadi.\nMe'yor: kapital ta'mirda 134(+4) mm; depo ta'mirida 144,0 mm dan ko'p emas.\nMe'yordan chiqsa — burtlar naplavka qilinib chizma o'lchamigacha tiklanadi."},
  {"nom": "Moslama Т1354.000 — burtlar nosimmetrikligi |A1−A2|", "rasm": "rasmlar/08-moslama-t1354-nosimmetriklik.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.5\nMoslama balkaning yuqori yuzasiga prizma zonasida o'rnatiladi va prizmaning upor qovurg'alariga qotiriladi.\n1000 mm li chizg'ich ГОСТ 427 bilan moslamaning o'lchov yuzasidan podpyatnikning upor yuzasigacha masofa o'lchanadi — «C1». Ikkinchi tomondan — «C2».\nMe'yor: |C1 − C2| ≤ 5 mm, bu |A1 − A2| ≤ 5 mm ga mos keladi."},
  {"nom": "Skolzun qalpog'i yeyilishi — «Р» tirqishini o'lchash", "rasm": "rasmlar/09-skolzun-qalpogi-p.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.1.6\nChizg'ich 300 mm ГОСТ 427 yon qirrasi bilan qalpoq ishchi yuzasining diagonaliga qo'yiladi; shchuplar to'plami Т914.21.000 bilan «Р» tirqishi o'lchanadi. Xuddi shu o'lchash IKKINCHI diagonal bo'yicha takrorlanadi.\nMe'yor: «Р» 2 mm dan ko'p emas. Ko'p bo'lsa — qalpoq yangisiga almashtiriladi. Kapital ta'mirda har doim yangi qalpoq o'rnatiladi.\nShchuplarni tayyorlash dopuski 0,05 mm dan oshmasligi kerak."},
  {"nom": "Buksa proyomi kengligi «a» — o'lchash sxemasi", "rasm": "rasmlar/10-buksa-proyomi-a-sxema.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.1 · Shablon Т914.009, ТУ 32 ЦВ 2504-2000\nO'lchash buksa proyomida yon ramaning pastidan 60 mm balandlikda, HAR TOMONDAN bajariladi.\nMe'yor: kapital ta'mirda 335±1 mm (18-9801 — 335(+3/−1)); depo ta'mirida 342,0 mm dan ko'p emas, 18-100 uchun — 338,0 mm dan ko'p emas."},
  {"nom": "Shablon Т914.009 — buksa proyomidagi ish holati", "rasm": "rasmlar/11-shablon-t914-009-ish-holati.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.1\nShablon buksa proyomiga kiritilib ishchi yuzalarga tegiziladi. Nazorat proyomning ikkala tomonida va ramaning ikkala buksa proyomida bajariladi.\nEng kengaygan qiymat me'yor bilan solishtiriladi."},
  {"nom": "Yo'naltiruvchilar kengligi «В» ni nazorat qilish", "rasm": "rasmlar/12-yonaltiruvchilar-kengligi-v.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.3 · Shablon Т914.009\n«В» ishchi yuzaning BUTUN balandligi bo'yicha — yuqori, o'rta va pastki qismlarda nazorat qilinadi.\nMe'yor: 160±1 mm; 18-9801 uchun — 160(+1/−2) mm. Depo ta'miridan chiqarishda 155 mm dan kam emas, 18-9801 uchun — 154 mm dan kam emas."},
  {"nom": "Priliv balandligi «h» va kanavkasimon yeyilish «К»", "rasm": "rasmlar/13-priliv-h-kanavka-k.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.2\nBuksa proyomining tayanch yuzasiga nazorat chizg'ichi ШП–400 ГОСТ 8026 qo'yiladi, ШЦ–I–125–0,1 ГОСТ 166 bilan priliv balandligi «h» va kanavka «К» o'lchanadi.\nMe'yor: «h» 3,0 mm dan kichik yoki katta bo'lishi mumkin (qiymat qayd etiladi); kanavka chuqurligi 2,0 mm dan ko'p emas, kengligi 20,0 mm dan ko'p emas (uzunligi tayanch yuza kengligiga teng)."},
  {"nom": "Priliv balandligi «h» ni shtangensirkul bilan o'lchash", "rasm": "rasmlar/14-priliv-h-olchash.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.2\nNazorat chizg'ichi baza sifatida qo'yiladi, shtangensirkul bilan chizg'ich yuzasidan priliv cho'qqisigacha bo'lgan balandlik o'lchanadi.\nChizg'ichsiz o'lchash mumkin emas — baza yuza bo'lmasa natija ishonchsiz bo'ladi."},
  {"nom": "Buksa proyomi tayanch yuzasini chizg'ich bilan nazorat qilish", "rasm": "rasmlar/15-tayanch-yuza-nazorati.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.11–5.2.12\nYeyilishga chidamli plastinaning notekis yeyilishi chizg'ich 300 mm va shchuplar bilan (5.1.6 dagi kabi, diagonallar bo'yicha) aniqlanadi — me'yor 2,0 mm dan ko'p emas.\nFriksion plankalarni o'rnatish uchun 4 ta teshik diametri ШЦЦ–I–125–0,01 bilan ikki o'zaro perpendikulyar yo'nalishda o'lchanadi — me'yor Ø 21(+0,84) mm."},
  {"nom": "Yon ramaning bazaviy o'lchami «М»", "rasm": "rasmlar/16-shtangen-m-bazaviy-olcham.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.4 · Штанген Т914.01.000, ТУ 32 ЦВ 2018-95\nO'lchash buksa proyomida ramaning pastidan 60 mm balandlikda, har tomondan bajariladi.\nMe'yor: «М» = 2185(+7/−5) mm; depo ta'miridan chiqarishda 2200,0 mm dan ko'p emas.\nBitta aravachadagi ikkita yon rama bazalari farqi 2 mm dan ko'p bo'lmasligi kerak."},
  {"nom": "Friksion plankalar orasidagi «L1» o'lchami", "rasm": "rasmlar/17-shtangen-fp-l1.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.5 · Штанген ФП Т914.02.000, ТУ 32 ЦВ 2019-95\nShtangalar uporlari bilan ressor proyomiga plankalarning yuqori qirralari bo'yicha o'rnatiladi, maksimal ochilib stopor vint bilan qotiriladi; ko'rsatkich ramka shkalasidan olinadi.\nO'lchash yon ramaning TASHQI va ICHKI tomonidan bajariladi.\nMe'yor: planka 10 mm — 642 mm dan kam emas; 16 mm — 630 mm dan kam emas. 18-100 (ramalar 2001-yildan keyin): ДР 648(+2,0/−3,6), КР 648(+1,6/−3,6); 2001-yilgacha: ДР 648(+2,0/−6,6), КР 648(+1,6/−6,6)."},
  {"nom": "«L1» va «L2» — plankalarning pastga kengayishi", "rasm": "rasmlar/18-shtangen-fp-l1-l2.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.5\nPolzunoklar plankalarning pastki qirralariga olib kelinadi, dvijoklar yuzalarga tekkuncha ochiladi; dvijok ko'rsatkichlari ramka ko'rsatkichiga qo'shiladi — «L2» olinadi.\nKengayish = L2 − L1. Me'yor: 4,0…10,0 mm. O'lchash tashqi va ichki tomondan bajariladi."},
  {"nom": "Plankalar noparallelligi — «Ж» va «З» nuqtalari", "rasm": "rasmlar/19-plankalar-noparallelligi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.5\nPlankalar orasidagi o'lchamlar yuqorida «Ж» nuqtalarida va pastda «З» nuqtalarida o'lchanadi.\nNoparallellik = eng katta va eng kichik o'lcham farqi. Me'yor: gorizontal tekislikda 3,0 mm dan ko'p emas."},
  {"nom": "Friksion planka yeyilishini o'lchash", "rasm": "rasmlar/20-planka-yeyilishi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.6\nShtangen ФП plankalarning yuqori qirralari bo'yicha o'rnatiladi; polzunok ko'rinadigan maksimal yeyilish joyiga olib kelinadi, dvijok plankaga tekkuncha chiqariladi. So'ngra shu o'lchash YEYILMAGAN joyda takrorlanadi — ikki ko'rsatkich farqi yeyilishni beradi.\nMe'yor: qo'zg'almas planka (10 mm) — 1,5 mm dan ko'p emas; harakatlanuvchi plankalarning umumiy yeyilishi — 2,0 mm dan ko'p emas, bir tomondan 1,5 mm dan ko'p emas."},
  {"nom": "«H1» va «H2» o'lchamlarining joylashuvi", "rasm": "rasmlar/21-h1-h2-joylashuvi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.7 · Штанген Н Т914.03.000, ТУ 32 ЦВ 2020-95\nH1 va H2 — friksion plankalar o'rnatiladigan yuzadan buksa proyomining tashqi yuzasigacha bo'lgan o'lchamlar.\nO'lchash friksion plankalar OLIB TASHLANGAN holda, buksa proyomining pastki yuzasidan 60 mm balandlikda, har tomondan bajariladi."},
  {"nom": "Shtangen Н bilan H1 va H2 ni o'lchash", "rasm": "rasmlar/22-shtangen-n-olchash.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.7\nQo'zg'almas oyoqcha ressor osma proyomiga kiritilib friksion plankaning privalochniy yuzasiga bosiladi; harakatlanuvchi oyoqcha buksa proyomining tashqi yuzasiga olib kelinib vint bilan qotiriladi. Ko'rsatkich shkaladan o'qiladi.\nMe'yor: |H1 − H2| ≤ 3,0 mm."},
  {"nom": "Friksion plankalarning zich yotishini nazorat qilish", "rasm": "rasmlar/23-plankalar-zich-yotishi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.8 · Набор щупов № 4 ТУ 3936-011-59489947-2007\nMe'yorlar: zaklepkalar oralig'idagi mahalliy zichmaslik — 1,0 mm dan ko'p emas, 18-100 uchun 0,5 mm dan ko'p emas.\nZaklepka boshi zonasida: 1 mm li shchup (18-100 uchun 0,5 mm) zaklepka sterjeniga yetmasligi kerak; tirqish bosh aylanasining 1/3 qismidan ortiq bo'lmasin.\nZaklepka boshining planka tekisligiga cho'kishi — 2,0 mm dan ko'p emas."},
  {"nom": "Privalochniy yuzalar orasidagi o'lcham va kengayish", "rasm": "rasmlar/24-privalochniy-yuzalar-668.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.9–5.2.10\nO'lchash KLEPKA ISHLARIDAN OLDIN, ШЦ–II–250–800–0,1 ГОСТ 166 bilan privalochniy yuzalarning yuqori va pastki qismida bajariladi.\nMe'yor: proyom o'lchami 668(−3) mm; har bir privalochniy yuzaning pastki qismidagi kengayish 2,0…5,0 mm.\nG'adir-budurlik ГОСТ 9378 namunalari bilan solishtiriladi: Ra 12,5 mkm dan ko'p emas."},
  {"nom": "Buksa zazorlari — aravacha o'qi BO'YLAB", "rasm": "rasmlar/25-zazorlar-boylama.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.13 · Приспособление Т914.21.000\nYon rama yo'naltiruvchilari bilan buksa korpusi orasidagi umumiy zazor Σδ = δ1 + δ2. Hisoblashda o'lchangan zazorlarning ENG KICHIK qiymatlari olinadi.\nMe'yor (aravacha o'qi bo'ylab): депо ta'miri — 5…14 mm, 18-100 uchun 3…12 mm; kapital ta'mir — 5…12 mm, 18-100 uchun 3…10 mm."},
  {"nom": "Buksa zazorlari — aravacha o'qiga KO'NDALANG", "rasm": "rasmlar/26-zazorlar-kondalang.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.2.13 · Приспособление Т914.21.000\nMe'yor (ko'ndalang): depo ta'miri — 5…13 mm, 18-100 uchun 5…12 mm; kapital ta'mir — 5…11 mm, 18-100 uchun 5…10 mm.\nO'lchash har bir buksa uchun alohida bajariladi."},
  {"nom": "Pona qiya yuzasi «X» ni o'lchash va «X/2» ni belgilash", "rasm": "rasmlar/27-pona-x-yarmi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.3.2 · Шаблон Т914.09.000, ТУ 32 ЦВ 2430-96\nNazorat boshlanishidan OLDIN chizg'ich 150 ГОСТ 427 yoki ШЦ–I–150–0,1 bilan ponaning qiya yuzasi o'lchami «X» o'lchanadi va o'rtasi «X/2» belgilanadi.\nO'lchash ponaning simmetriya o'qi bo'yicha o'rta kesimda bajariladi.\nYoriqlar lupa ЛП-1-4 ГОСТ 25706 (≥4 karra) bilan tekshiriladi — qattiqlik qovurg'alarida yoriq ruxsat etilmaydi (band 5.3.1)."},
  {"nom": "Shablon Т914.09.000 ning ponadagi ish holati", "rasm": "rasmlar/28-shablon-pona-ish-holati.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.3.2\nShablon ponaga o'rnatilib asosiga zich bosiladi; ponaning pastki chiqig'i shablonning ichki old vertikal va gorizontal tayanch qirralariga zich tegishi shart.\nVERTIKAL yeyilish: gorizontal dvijok ko'rsatkichidan 2 mm AYIRILADI.\nQIYA yeyilish: «X/2» ga chizg'ich qo'yilib dvijok tekkuncha suriladi; natijaga chizg'ich qalinligi «Y» QO'SHILADI.\nUmumiy yeyilish = vertikal + qiya. Me'yor: depo ta'mirida 3,0 mm dan ko'p emas, bir tomondan 2,0 mm dan ko'p emas. Kapital ta'mirda ponalar yangisiga almashtiriladi."},
  {"nom": "Upor burt uzunligi «С» ni o'lchash", "rasm": "rasmlar/29-pona-upor-burt-c.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.3.2\nPonaning vertikal tekisligi yuqori qismida ШЦ–I–150–0,1 ГОСТ 166 bilan upor burt uzunligi «С» eng katta yeyilish joyida o'lchanadi; ikkinchi burt ham xuddi shunday.\nMe'yor: M1698.00.003 (-01), 1699.04.007-01, ВАГР-0113.50.00.002-01 chizmalari — 66 mm dan kam emas; 100.30.001-1, 2128-05.50.00.005 — 67 mm dan kam emas. Chizma 1699.04.007 bo'yicha «С» o'lchanmaydi."},
  {"nom": "Yangi pona — asos uzunligi «В» va «С»", "rasm": "rasmlar/30-yangi-pona-b-c.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.3.3\n«В» kronsirkul bilan o'lchanadi: bir uchi vertikal yuzaga, ikkinchisi o'rta kesimdagi «A» chiqig'iga tiriladi, o'lcham 300 mm li chizg'ichga ko'chiriladi. Me'yor: 212 ± 2 mm.\n«С» — vertikal tekislikdan upor burtgacha, ШЦ–I–150–0,1 bilan. Me'yor: 69 ± 1 mm (СЧ 35 chizmalari) yoki 71 ± 2 mm (Сталь 20Л chizmalari)."},
  {"nom": "Yangi pona — qiya tekislik kengligi «D»", "rasm": "rasmlar/31-yangi-pona-d.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.3.3\nPonaning qiya yuzasi kengligi «D» ШЦ–I–150–0,1 ГОСТ 166 bilan o'lchanadi.\nMe'yor: 130 ± 2 mm."},
  {"nom": "Yangi pona — o'yiq chuqurligi «Z» ni aniqlash", "rasm": "rasmlar/32-yangi-pona-z.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.3.3\nQiya yuza o'lchami «X» o'lchanib o'rtasi «X/2» belgilanadi; 150 mm li chizg'ich qiya yuzaga qo'yilib, № 1 yoki № 2 to'plamdagi shchuplar bilan o'yiq chuqurligi baholanadi.\nMe'yor: «Z» = 2 ± 1 mm. Asos uzunligi «В» = 212 ± 2 mm."},
  {"nom": "Prujina balandligini shtangenglubinomer bilan o'lchash", "rasm": "rasmlar/33-prujina-balandligi.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.4.2 · ШГ–300–0,1 ГОСТ 162 + плита ГОСТ 10905\nTASHQI prujina: shtangenglubinomer prujina ICHIGA joylashtiriladi, ramka asosi ikkita uchi bilan toretsga tayanadi, shtanga plitaga tiraladi.\nICHKI prujina: asbob prujina MARKAZIGA joylashtiriladi.\nMe'yor: 249(+6/−3) mm; 18-100, 18-101 — 249(+7/−2) mm (1989–2012 y.), 249(+6/−2) mm (2012–2015 y.). Komplektga tanlashda balandlik farqi 4 mm dan oshmasligi kerak.\nTayanch yuzalar o'ram uchidan aylananing 0,7…0,8 yoyi bo'yicha ishlangan bo'lishi kerak (ГОСТ 1452-2011)."},
  {"nom": "Tashqi prujinalarning ichki diametrini kalibrlash", "rasm": "rasmlar/34-kalibr-tashqi-prujina.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.4.3 · Калибр стакан-пробка Т914.22.000\nMuvofiqlik kalibr O'Z OG'IRLIGI ostida prujinaning butun uzunligi bo'yicha o'tsa aniqlanadi — kalibrni kuch bilan bosish taqiqlanadi.\nKalibrlar shu bilan birga prujina geometriyasining ruxsat etilgan buzilish chegaralarini ham belgilaydi."},
  {"nom": "Ichki prujinalarning tashqi diametrini kalibrlash", "rasm": "rasmlar/35-kalibr-ichki-prujina.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.4.3–5.4.4 · Калибр-стакан Т914.23.000\nKalibr o'z og'irligi ostida prujinaning butun uzunligi bo'yicha o'tishi kerak.\nPrutok diametri ШЦ–I–125–0,1 ГОСТ 166 bilan o'lchanadi. Me'yor: 29/20 mm; 18-9597 — 30/21 mm; 18-9770, 18-2128, 18-7055, 18-9801, 18-9918, 18-9922, 18-1750 — 29/20 yoki 30/21 mm; 18-100, 18-101 — tashqi 30 mm (2015 y.gacha), ichki 19 mm (1989 y.gacha) yoki 21 mm (1989–2015 y.)."},
  {"nom": "Moslama Т914.18.000 — ponalar holatini nazorat qilish", "rasm": "rasmlar/36-moslama-t914-18-pona-holati.jpg", "izoh": "РД 32 ЦВ 050-2020, band 5.5\nMoslama nadressor balkasining tayanch yuzasiga o'rnatiladi va 100 mm radius bilan prujinaga tiraladi; koromislo o'lchov uchi bilan ponaning pastki yuzasiga olib boriladi, ko'rsatkich shkaladan o'qiladi. Ikkinchi pona ham xuddi shunday o'lchanadi.\nMe'yor: DEPO ta'mirida — hech bir ponaning ko'tarilishi (завышение) ruxsat etilmaydi, pasayish 12 mm dan ko'p emas. KAPITAL ta'mirda — bitta ressor osmasining ponalari 4,0…12,0 mm ga pasaytirilgan bo'lishi kerak.\nNazorat aravacha yig'ilib vagon ostiga podkatka qilingandan keyin bajariladi."},
];

/* 7) DEFEKTATSIYA KARTALARI — nuqson va qaror
      Manba: РД 32 ЦВ 052-2009, Ilova Ж (majburiy) */
const KARTALAR = [
  {"nom": "Yon rama — pozitsiyalar sxemasi", "rasm": "rasmlar_dk/dk-rama-sxema.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 1-varaq (4 varaqdan)\n1 — buksa proyomining ichki burchagi; 2 — buksalar uchun yo'naltiruvchi tekislik (ichki chelyust); 3 — qiya poyasning vertikal devori; 4 — qiya poyas; 5 — ressor proyomi stoykasi; 6 — ressor proyomining pastki burchagi; 7 — ressor proyomining kuchaytirish qovurg'asi; 8 — friksion pona uchun yo'naltiruvchi burtcha; 9 — pastki poyas; 10 — poddomkrat yostig'i; 11 — buksalar uchun yo'naltiruvchi tekislik (tashqi chelyust); 12 — buksa proyomining tashqi burchagi; 13 — buksa proyomining tayanch yuzasi; 14 — buksa proyomi ustidagi vertikal devor; 15 — buksa proyomi ustidagi texnologik teshik qirrasi; 16 — texnologik oyna qirrasi; 17 — friksion plankalarni biriktirish; 18 — yuqori poyas; 19 — ressor proyomining yuqori burchagi; 20 — bashmak osmasi valigi uchun priliv; 21 — triangel osmasi kronshteyni; 22 — buksa proyomi ustidagi javon (tavr kesimli ramalar uchun); 23 — buksa proyomi ustidagi kuchaytirish qovurg'asi (tavr kesimli ramalar uchun)."},
  {"nom": "Nadressor balkasi — pozitsiyalar sxemasi", "rasm": "rasmlar_dk/dk-balka-sxema.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 1-varaq (3 varaqdan)\n1 — skolzun tayanchi; 2 — yuqori poyasdagi texnologik teshik; 3 — yuqori poyas; 4 — podpyatnikning tashqi burti; 5 — podpyatnikning ichki burti; 6 — podpyatnikning tayanch yuzasi; 7 — pona uchun qiya tekislik; 8 — cheklovchi burt; 9 — prujinalarni cheklovchi upor qovurg'asi; 10 — pastki poyas; 11 — yon devor; 12 — pastki poyasning ichki yuzasi; 13 — kolonka; 14 — yuqori poyasning ichki yuzasi."},
  {"nom": "Yon rama — buksa proyomining ichki va tashqi burchagi (poz. 1 va 12)", "rasm": "rasmlar_dk/dk-rama-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 2-varaq · R55 radiusi zonasi\nYORIQ — vizual ko'rik, o'lchash, МПК (chizg'ich, defektoskop) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nYEYILISHGA CHIDAMLI PLASTINADAN ZARBA IZLARI (зарубы) — chuqurligi 1 mm dan katta → BRAK.\nKESUVCHI ASBOB IZLARI — o'lchamidan qat'i nazar → BRAK.\nPAYVAND-NAPLAVKA IZLARI — o'lchamidan qat'i nazar → BRAK.\nIzoh: R55 — buksa proyomining gorizontal tayanch yuzasidan vertikal yo'naltiruvchi yuzaga o'tish radiusi va radius qirralaridan 10 mm gacha bo'lgan yon yuzalar."},
  {"nom": "Yon rama — buksa proyomining tayanch yuzasi (poz. 13)", "rasm": "rasmlar_dk/dk-rama-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 2-varaq\nYORIQ — vizual ko'rik, o'lchash (chizg'ich) → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nKANAVKASIMON YEYILISH — o'lchash (chizg'ich, shtangensirkul):\n · kengligi ≤ 20 mm VA chuqurligi ≤ 2 mm → stanokda mexanik ishlov berish;\n · chuqurligi > 2 mm (priliv 3 mm bo'lganda) → BRAK;\n · chuqurligi > 2 mm (priliv 3 mm dan katta bo'lganda) → stanokda mexanik ishlov;\n · kengligi > 20 mm → BRAK.\nPAYVAND-NAPLAVKA IZLARI — o'lchamidan qat'i nazar → BRAK.\nTa'mirdan keyin: vizual ko'rik va o'lchash."},
  {"nom": "Yon rama — buksalar uchun yo'naltiruvchi tekisliklar / upor yuzalar (poz. 2 va 11)", "rasm": "rasmlar_dk/dk-rama-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 2-varaq\nYEYILISH — o'lchash (shtangensirkul, shablon):\n · buksa proyomi kengligi bo'yicha > 8 mm → BRAK;\n · buksa proyomi kengligi bo'yicha ≤ 8 mm → naplavka bilan ta'mirlash;\n · yo'naltiruvchilar kengligi bo'yicha > 4 mm → BRAK;\n · yo'naltiruvchilar kengligi bo'yicha ≤ 4 mm → naplavka bilan ta'mirlash.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nTa'mirdan keyin: vizual ko'rik va o'lchash."},
  {"nom": "Yon rama — buksa proyomi ustidagi vertikal devor (poz. 14)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nBu pozitsiyalarda yoriqni payvandlashga RUXSAT ETILMAYDI — uzunligidan qat'i nazar detal brak qilinadi."},
  {"nom": "Yon rama — buksa proyomi ustidagi texnologik teshik qirrasi (poz. 15)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nBu pozitsiyalarda yoriqni payvandlashga RUXSAT ETILMAYDI — uzunligidan qat'i nazar detal brak qilinadi."},
  {"nom": "Yon rama — buksa proyomi ustidagi javon va uning qirrasi (tavr kesim) (poz. 22)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nBu pozitsiyalarda yoriqni payvandlashga RUXSAT ETILMAYDI — uzunligidan qat'i nazar detal brak qilinadi."},
  {"nom": "Yon rama — buksa proyomi ustidagi kuchaytirish qovurg'asi (tavr kesim) (poz. 23)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nBu pozitsiyalarda yoriqni payvandlashga RUXSAT ETILMAYDI — uzunligidan qat'i nazar detal brak qilinadi."},
  {"nom": "Yon rama — texnologik oyna qirrasi (poz. 16)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nBu pozitsiyalarda yoriqni payvandlashga RUXSAT ETILMAYDI — uzunligidan qat'i nazar detal brak qilinadi."},
  {"nom": "Yon rama — ressor proyomi stoykasi (poz. 5)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK, ta'mirga tegishli emas.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nBu pozitsiyalarda yoriqni payvandlashga RUXSAT ETILMAYDI — uzunligidan qat'i nazar detal brak qilinadi."},
  {"nom": "Yon rama — qiya poyas va uning vertikal devori (poz. 3 va 4)", "rasm": "rasmlar_dk/dk-rama-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 3-varaq\nYORIQ — vizual ko'rik, o'lchash va МПК (metall chizg'ich, defektoskop) → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nDiqqat: bu zona МПК ni ham talab qiladi — qiya poyas eng ko'p kuchlanish oladigan joylardan biri."},
  {"nom": "Yon rama — ressor proyomining pastki va yuqori burchagi (poz. 6 va 19)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK."},
  {"nom": "Yon rama — ressor proyomining kuchaytirish qovurg'asi (poz. 7)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\nYORIQ — vizual ko'rik va o'lchash → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK."},
  {"nom": "Yon rama — pastki va yuqori poyas (poz. 9 va 18)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich) → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nPoyaslar ramaning asosiy yuk ko'taruvchi elementlari — ularda hech qanday yoriq ta'mirlanmaydi."},
  {"nom": "Yon rama — triangel osmasi kronshteyni (poz. 21)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich):\n · uzunligi < 32 mm → PAYVAND bilan ta'mirlash;\n · uzunligi ≥ 32 mm → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nTa'mirdan keyin: vizual ko'rik."},
  {"nom": "Yon rama — bashmak osmasi valigi prilivining devori (poz. 20)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\nYORIQ — vizual ko'rik va o'lchash:\n · BO'YLAMA yoriq → PAYVAND bilan ta'mirlash;\n · KO'NDALANG yoriq → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nTa'mirdan keyin: vizual ko'rik."},
  {"nom": "Yon rama — friksion pona uchun yo'naltiruvchi burtcha (poz. 8)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\nYORIQ — vizual ko'rik va o'lchash → PAYVAND bilan ta'mirlash.\nUCHISH (откол) — vizual ko'rik → PAYVAND bilan ta'mirlash (yangi burtcha payvandlab o'rnatiladi).\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nTa'mirdan keyin: vizual ko'rik."},
  {"nom": "Yon rama — friksion plankalarni biriktirish, «quloqchalar» (poz. 17)", "rasm": "rasmlar_dk/dk-rama-v4.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Yon rama kartasi, 4-varaq\n«QULOQCHALAR»NING UCHISHI — vizual ko'rik:\n · diagonal bo'yicha joylashgan ≤ 2 ta → PAYVAND bilan ta'mirlash;\n · 2 tadan ko'p → BRAK.\nTa'mirdan keyin: vizual ko'rik."},
  {"nom": "Nadressor balkasi — skolzun tayanchi (poz. 1)", "rasm": "rasmlar_dk/dk-balka-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 2-varaq\nYORIQ — vizual ko'rik:\n · yuqori poyasga O'TUVCHI → BRAK;\n · yuqori poyasga o'tmaydigan → PAYVAND bilan ta'mirlash.\nYEYILISH — vizual ko'rik va o'lchash (shtangensirkul, shablon) → PAYVAND bilan ta'mirlash.\nSINISH (излом) — vizual ko'rik → PAYVAND bilan ta'mirlash.\nTa'mirdan keyin: vizual ko'rik, o'lchash."},
  {"nom": "Nadressor balkasi — yuqori poyas (poz. 3)", "rasm": "rasmlar_dk/dk-balka-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 2-varaq\nYORIQ — vizual ko'rik va o'lchash (metall chizg'ich):\n · KO'NDALANG → BRAK;\n · BO'YLAMA, uzunligi > 250 mm → BRAK;\n · BO'YLAMA, uzunligi ≤ 250 mm → PAYVAND bilan ta'mirlash.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nEslatma: balkaning bo'ylama o'qiga 30° dan katta burchakdagi yoriq KO'NDALANG hisoblanadi."},
  {"nom": "Nadressor balkasi — podpyatnikning tashqi burti (poz. 4)", "rasm": "rasmlar_dk/dk-balka-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 2-varaq\nYORIQ — vizual ko'rik va МПК (defektoskop):\n · tutashgan yuzalarga CHIQMAYDIGAN → PAYVAND bilan ta'mirlash;\n · tutashgan yuzalarga CHIQADIGAN → BRAK.\nTa'mirdan keyin: vizual ko'rik va МПК."},
  {"nom": "Nadressor balkasi — podpyatnikning ichki burti (poz. 5)", "rasm": "rasmlar_dk/dk-balka-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 2-varaq\nYORIQ — vizual ko'rik va МПК (defektoskop):\n · tutashgan yuzalarga CHIQMAYDIGAN → PAYVAND bilan ta'mirlash;\n · tutashgan yuzalarga CHIQADIGAN → BRAK.\nTa'mirdan keyin: vizual ko'rik va МПК."},
  {"nom": "Nadressor balkasi — podpyatnikning tayanch yuzasi (poz. 6)", "rasm": "rasmlar_dk/dk-balka-v2.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 2-varaq\nYORIQ — vizual ko'rik, o'lchash, МПК (chizg'ich, defektoskop):\n · umumiy uzunligi > 250 mm → BRAK;\n · umumiy uzunligi ≤ 250 mm → PAYVAND bilan ta'mirlash.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nYEYILISH — o'lchash (shablon, kronsirkul):\n · qolgan qalinlik ≥ 18 mm → NAPLAVKA bilan ta'mirlash;\n · qolgan qalinlik < 18 mm → BRAK.\nTa'mirdan keyin: vizual ko'rik, o'lchash, МПК."},
  {"nom": "Nadressor balkasi — pona uchun qiya tekislik (poz. 7)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYORIQ — vizual ko'rik, o'lchash, МПК (chizg'ich, defektoskop):\n · KO'NDALANG → BRAK;\n · BO'YLAMA, cheklovchi burtga chiqmaydigan → PAYVAND bilan ta'mirlash;\n · BO'YLAMA, cheklovchi burtga chiqadigan → BRAK.\nYEYILISH — vizual ko'rik va o'lchash (ULTRATOVUSH QALINLIK O'LCHAGICH):\n · qolgan qalinlik ≥ 7 mm → NAPLAVKA bilan ta'mirlash;\n · qolgan qalinlik < 7 mm → plastina-vstavkani payvandlab ta'mirlash.\nTa'mirdan keyin: vizual ko'rik, МПК."},
  {"nom": "Nadressor balkasi — cheklovchi burt bilan qiya tekislik orasidagi burchak (poz. 7 va 8)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYORIQ — vizual ko'rik va МПК:\n · yuqori poyasga O'TMAYDIGAN → PAYVAND bilan ta'mirlash;\n · yuqori poyasga O'TADIGAN → BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nTa'mirdan keyin: vizual ko'rik va МПК."},
  {"nom": "Nadressor balkasi — cheklovchi burt (poz. 8)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYEYILISH — vizual ko'rik va o'lchash (shtangensirkul):\n · qolgan qalinlik ≥ 10 mm → NAPLAVKA bilan ta'mirlash;\n · qolgan qalinlik < 10 mm → BRAK.\nTa'mirdan keyin: vizual ko'rik, o'lchash."},
  {"nom": "Nadressor balkasi — prujinalarni cheklovchi upor qovurg'asi (poz. 9)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYEYILISH — vizual ko'rik va o'lchash (shtangensirkul) → PAYVAND bilan ta'mirlash.\nTa'mirdan keyin: vizual ko'rik."},
  {"nom": "Nadressor balkasi — pastki poyas (poz. 10)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYORIQ — vizual ko'rik va МПК (defektoskop) → o'lchamidan qat'i nazar BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK.\nPastki poyas — balkaning eng ko'p cho'zilish kuchlanishini oladigan qismi, shuning uchun yoriq umuman ta'mirlanmaydi."},
  {"nom": "Nadressor balkasi — yon devor (poz. 11)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYORIQ — vizual ko'rik → o'lchamidan qat'i nazar BRAK.\nO'TUVCHI QUYMA NUQSON — vizual ko'rik → BRAK."},
  {"nom": "Nadressor balkasi — kolonka (poz. 13)", "rasm": "rasmlar_dk/dk-balka-v3.jpg", "izoh": "РД 32 ЦВ 052-2009, Ilova Ж (majburiy) · Nadressor balkasi kartasi, 3-varaq\nYORIQ — vizual ko'rik → o'lchamidan qat'i nazar BRAK.\nBu 9.2-banddagi qoidaga mos: podpyatnikning ichki kolonkasi va kuchaytirish qovurg'alaridagi yoriqlar uzunligidan qat'i nazar ta'mirga tegishli emas."},
];

/* 6) DEFEKTOSKOP NAZORATIDAN O'TUVCHI ZONALAR
      Manba: РД 32 ЦВ 052-2009 (7-bo'lim) va ПР НК В.3 (2019-yil tahriri) */
const ZONALAR = [
  {"nom": "Yon rama (tip 2) — nazorat zonalari", "rasm": "rasmlar_nk/zona-yonrama.jpg", "izoh": "РД 32 ЦВ 052-2009, band 7.2 · 7.2-jadval\nUsul: magnitoxukukli nazorat (МПК). Aniqlanadigan nuqson: bo'ylama va ko'ndalang yoriqlar.\nZonalar: 1 — buksa proyomining tashqi burchagi; 2 — buksa proyomining ichki burchagi; 3 — qiya poyas; 4 — buksa proyomi tashqi burchagining vertikal devori; 5 — buksa proyomi ichki burchagining vertikal devori; 6 — qiya poyasning vertikal devori; 7 — buksa proyomi tashqi burchagining qirrasi.\nChizmada: а — yon ramaning quticha kesimi, б — tavr kesimi. O'lchamlar 45 mm, 15 mm, 50 mm va 100 mm — majburiy nazorat zonasining chegaralari.\nZonalar shtrixlangan holda ko'rsatilgan."},
  {"nom": "Nadressor balkasi (tip 2) — nazorat zonalari", "rasm": "rasmlar_nk/zona-nadressor.jpg", "izoh": "РД 32 ЦВ 052-2009, band 7.2 · 7.2-jadval\nUsul: magnitoxukukli nazorat (МПК). Aniqlanadigan nuqson: bo'ylama va ko'ndalang yoriqlar.\nZonalar: 1 — pastki poyas; 2 — pona uchun qiya tekislik; 3 — podpyatnikning ichki burti; 4 — podpyatnikning tayanch yuzasi; 5 — cheklovchi burt bilan qiya tekislik orasidagi burchak; 6 — podpyatnikning tashqi burti.\nPastki poyas bo'yicha majburiy nazorat zonasi markazdan har tomonga 520 mm, balandligi 50 mm."},
  {"nom": "Yuk vagon aravachasi detallari — nazorat usullari", "rasm": "rasmlar_nk/jadval-4-1.jpg", "izoh": "ПР НК В.3, band 4.1.4 · 4.1-jadval\nQuyma detallar (nadressor balkasi, balansir, yon rama, shkvoren balkasi, transportyor balkalari, biriktiruvchi balka) — faqat МПК.\nShtamp-payvand detallar (nadressor balkasi, rama, biriktiruvchi balka) — МПК.\nRessor osmasi detallari (КВЗ-И2, ЦМВ va boshq.) va shkvoren — МПК yoki ВТК.\nUsullar MAJBURIY. Har bir detalga harakat tarkibidan olinib, tozalangandan keyin qo'llaniladi."},
  {"nom": "Yo'lovchi vagon aravachasi detallari — usullar (1-qism)", "rasm": "rasmlar_nk/jadval-4-2a.jpg", "izoh": "ПР НК В.3, band 4.1.4 · 4.2-jadval\nShtamp-payvand detallar (КВЗ-ЦНИИ, ТВЗ-ЦНИИ, КВЗ-5, lyulkasiz tipdagi va GP-200 aravachalarining nadressor balkasi va ramasi) — МПК.\nRessor va buksa osmasi detallari (buksa povodogi, shpinton vtulkasi, skolzun qutisi, prujinalar, ЦЛП ramkasi, serga) — МПК yoki ВТК.\nQolgan detallar (valiklar, saqlovchi sterjen, osma tortqilari, ИВП Дергачева detallari) — МПК."},
  {"nom": "Yo'lovchi vagon aravachasi detallari — usullar (2-qism, GP-200)", "rasm": "rasmlar_nk/jadval-4-2b.jpg", "izoh": "ПР НК В.3, band 4.1.4 · 4.2-jadvalning oxiri\nGP-200 aravachasining markaziy ressor osmasi detallari (yo'naltiruvchi sterjen, pichoqsimon tayanch, tayanch qism, barmoqlar, osma, egar qismi, poddon sapfasi) — МПК.\nYo'lovchi vagonlarining shkvoreni — МПК yoki ВТК (restoran-vagonlardan tashqari).\nDetal НК talablariga faqat qo'llanilgan BARCHA usullar bo'yicha muvofiq chiqsa yaroqli hisoblanadi (band 4.1.5)."},
  {"nom": "ВТК parametrlari — sezgirlik va skanerlash qadami", "rasm": "rasmlar_nk/jadval-5-1.jpg", "izoh": "ПР НК В.3, band 5.1.2 · 5.1-jadval\nSkanerlash qadami: qo'llanilayotgan ВТП diametridan katta bo'lmasin.\nAniqlanishi kerak bo'lgan sun'iy yuza nuqsoni: chuqurligi 3000 ± 100 mkm, kengligi 500 mkm dan ko'p emas.\nIstisno — g'adir-budurligi 40 ≤ Rz < 160 mkm bo'lgan detallar (markaziy va buksa osmasi prujinalari, shpinton vtulkasi): chuqurlik 500 ± 100 mkm, kenglik 150 mkm dan ko'p emas.\nRz < 40 mkm bo'lgan detallar uchun: chuqurlik 150 ± 50 mkm, kenglik 30 mkm dan ko'p emas."},
  {"nom": "МПК parametrlari — ressor va buksa osmasi detallari", "rasm": "rasmlar_nk/jadval-5-2.jpg", "izoh": "ПР НК В.3, band 5.1.3 · 5.2-jadval\nNazorat usuli: СПП — qo'yilgan maydon usuli (magnit indikatori magnitlash bilan bir vaqtda suriladi).\nDetal yuzasidagi Ht (tangensial tashkil etuvchi): 20 А/см dan kam emas.\nMagnitlash turi: qutbli (полюсное).\nNamunadagi sun'iy nuqsonlarning ochilish kengligi: 20 dan 30 mkm gacha, yo'nalishi — ko'ndalang.\nRessor va buksa osmasi detallari, GP-200 markaziy ressor osmasi detallari va shkvoren uchun."},
  {"nom": "МПК parametrlari — quyma va shtamp-payvand detallar", "rasm": "rasmlar_nk/jadval-5-3.jpg", "izoh": "ПР НК В.3, band 5.2.3 · 5.3-jadval\nNazorat usuli: СПП. Detal yuzasidagi Ht: 20 А/см dan kam emas.\nMagnitlash turi: qutbli, sirkulyar, kombinatsiyalangan yoki aylanuvchi magnit maydonida.\nSun'iy nuqsonlarning ochilish kengligi: 20 dan 30 mkm gacha; yo'nalishi — ko'ndalang va bo'ylama, uzunligi 5 mm dan ko'p emas.\nМПК ikki bosqichda bajariladi: nuqsonlarni tozalash/kesishdan keyin va payvand-naplavka ishlaridan keyin qayta nazorat (band 5.2.1)."},
  {"nom": "Lyulka va markaziy osma valiklari — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-1.jpg", "izoh": "ПР НК В.3, 5.1-rasm · «Валики люлечного и центрального (люлечного) подвешивания»\nNazorat usuli: МПК yoki ВТК (yuk); МПК (yo'lovchi). Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Lyulka osmasi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-2.jpg", "izoh": "ПР НК В.3, 5.2-rasm · «Люлечная подвеска»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Elliptik ressor uchliklari — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-3.jpg", "izoh": "ПР НК В.3, 5.3-rasm · «Наконечники эллиптической рессоры»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Elliptik ressor xomuti — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-4.jpg", "izoh": "ПР НК В.3, 5.4-rasm · «Хомут эллиптической рессоры»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Osma tortqisi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-5.jpg", "izoh": "ПР НК В.3, 5.5-rasm · «Тяга подвески»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Shkvorenlar — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-6.jpg", "izoh": "ПР НК В.3, 5.6-rasm · «Шкворни»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Lyulka (tayanch) balkasi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-7.jpg", "izoh": "ПР НК В.3, 5.7-rasm · «Люлечная (опорная) балка»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Buksa povodogi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-8.jpg", "izoh": "ПР НК В.3, 5.8-rasm · «Буксовый поводок»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Shpinton vtulkasi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-9.jpg", "izoh": "ПР НК В.3, 5.9-rasm · «Втулка шпинтона»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Skolzun qutisi (ТВЗ-ЦНИИ, КВЗ-ЦНИИ) — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-10.jpg", "izoh": "ПР НК В.3, 5.10-rasm · «Коробка скользуна тележек ТВЗ-ЦНИИ и КВЗ-ЦНИИ»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Markaziy va buksa osmasi prujinalari — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-11.jpg", "izoh": "ПР НК В.3, 5.11-rasm · «Пружины центрального и буксового подвешивания»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "ЦЛП ramkasi (ТВЗ-ЦНИИ, КВЗ-ЦНИИ) — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-12.jpg", "izoh": "ПР НК В.3, 5.12-rasm · «Рамка ЦЛП тележек ТВЗ-ЦНИИ и КВЗ-ЦНИИ»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Markaziy osma sergasi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-13.jpg", "izoh": "ПР НК В.3, 5.13-rasm · «Серьга центрального подвешивания»\nNazorat usuli: МПК yoki ВТК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Saqlovchi sterjen (КВЗ-ЦНИИ-I) — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-14.jpg", "izoh": "ПР НК В.3, 5.14-rasm · «Стержень предохранительный тележки КВЗ-ЦНИИ-I»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Osma tortqisi — КВЗ-ЦНИИ-I — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-15.jpg", "izoh": "ПР НК В.3, 5.15-rasm · «Тяга подвески тележки КВЗ-ЦНИИ-I»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Osma tortqisi — КВЗ-ЦНИИ-II — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-16.jpg", "izoh": "ПР НК В.3, 5.16-rasm · «Тяга подвески тележки КВЗ-ЦНИИ-II»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Osma tortqisi — КВЗ-ЦНИИ-М — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-17.jpg", "izoh": "ПР НК В.3, 5.17-rasm · «Тяга подвески тележки КВЗ-ЦНИИ-М»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Qotiruvchi serga (lyulkasiz tip) — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-18.jpg", "izoh": "ПР НК В.3, 5.18-rasm · «Серьга фиксирующая тележек безлюлечного типа»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "Bo'ylama povodok tortqisi (lyulkasiz tip) — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-19.jpg", "izoh": "ПР НК В.3, 5.19-rasm · «Тяга продольного поводка тележек безлюлечного типа»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "ИВП Дергачева povodok tortqisi — chap — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-20.jpg", "izoh": "ПР НК В.3, 5.20-rasm · «Тяга поводков ИВП Дергачева левая»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "ИВП Дергачева povodok tortqisi — o'ng — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-21.jpg", "izoh": "ПР НК В.3, 5.21-rasm · «Тяга поводков ИВП Дергачева правая»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "ИВП Дергачева povodok bolti — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-22.jpg", "izoh": "ПР НК В.3, 5.22-rasm · «Болт поводков ИВП Дергачева»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — yo'naltiruvchi sterjen — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-23.jpg", "izoh": "ПР НК В.3, 5.23-rasm · «Направляющий стержень тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — osmaning pichoqsimon tayanchi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-24.jpg", "izoh": "ПР НК В.3, 5.24-rasm · «Ножевая опора подвески тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — tayanch qismi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-25.jpg", "izoh": "ПР НК В.3, 5.25-rasm · «Опорная часть тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — avariya osmasi barmog'i — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-26.jpg", "izoh": "ПР НК В.3, 5.26-rasm · «Палец аварийного подвешивания тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — osma yuqori tayanchining barmog'i — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-27.jpg", "izoh": "ПР НК В.3, 5.27-rasm · «Палец верхней опоры подвески тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — osma pastki tayanchining barmog'i — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-28.jpg", "izoh": "ПР НК В.3, 5.28-rasm · «Палец нижней опоры подвески тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — osma — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-29.jpg", "izoh": "ПР НК В.3, 5.29-rasm · «Подвеска тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — egar qismi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-30.jpg", "izoh": "ПР НК В.3, 5.30-rasm · «Седельная часть тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
  {"nom": "GP-200 — poddon sapfasi — nazorat zonalari", "rasm": "rasmlar_nk/zona-5-31.jpg", "izoh": "ПР НК В.3, 5.31-rasm · «Цапфа поддона тележки GP-200»\nNazorat usuli: МПК. Arbitraj usul — МПК (band 5.1.1).\nNazorat zonalari chizmada shtrixlangan va yo'g'on chiziq bilan ko'rsatilgan (band 5.1.4). Aniqlanadigan nuqson — yuza uzluksizligining buzilishi (yoriqlar).\nNazoratdan oldin detal metallgacha tozalanadi: zang, ifloslik, moy va bo'yoq olib tashlanadi (band 6.1.2)."},
];

/* 4) TESTLAR — "togri" to'g'ri javob indeksi (0 dan boshlanadi) */
const TESTLAR = [
  {
    nom: "Mehnat muhofazasi — asosiy test",
    savollar: [
      {"savol":"Payvandlash ishlarida qanday himoya vositasi majburiy?","variantlar":["Qo'lqop","Payvandchi niqobi","Shlyapa","Ko'zoynak (oddiy)"],"togri":1},
      {"savol":"Elektr asboblari bilan ishlashdan oldin nima tekshiriladi?","variantlar":["Rangi","Og'irligi","Izolyatsiya holati","Narxi"],"togri":2},
      {"savol":"Yong'in chiqqanda birinchi navbatda nima qilinadi?","variantlar":["Ishni davom ettirish","Signal berish va sexni bo'shatish","Derazani ochish","Hech narsa"],"togri":1}
    ],
  },
  {
    nom: "Telejka mexanikasi — bilim testi",
    savollar: [
      {"savol":"G'ildirak podshipnigi qachon almashtiriladi?","variantlar":["Yiliga bir marta majburiy","Ovoz/tebranish paydo bo'lganda","Hech qachon","Faqat rangi o'zgarsa"],"togri":1},
      {"savol":"Gidravlik tizimda bosim pasayishi odatda nimadan darak beradi?","variantlar":["Moy yetarli","Shlangda sizish","Harorat past","Muammo yo'q"],"togri":1},
      {"savol":"Payvand chok sifatini tekshirishning eng sodda usuli?","variantlar":["Vizual ko'rik","Hidini bilish","Rangini solishtirish","Og'irligini o'lchash"],"togri":0}
    ],
  },
];
