/* ============================================================
   IMTIHON SAVOLLARI — telejka ta'mirlash sexi
   Manbalar: РД 32 ЦВ 050-2020, РД 32 ЦВ 052-2009, ПР НК В.3
   12 etap, 250 ta savol. Har bir savol hujjat bandiga asoslangan.
   ============================================================ */
const ETAPLAR = [
  {
    nom: "Aravacha tuzilishi va atamalar",
    daraja: "Boshlang'ich",
    tavsif: "Tip 2 aravachaning qismlari, materiallar, ta'mir turlari va hujjatlar tizimi.",
    savollar: [
      {"savol": "ГОСТ 9246 bo'yicha tip 2 aravachaning yuk ko'taruvchi asosi nechta katta quyma detaldan iborat?", "variantlar": ["To'rtta", "Uchta", "Beshta", "Ikkita"], "togri": 1, "izoh": "Ikkita yon rama va bitta nadressor balkasi — shuning uchun «uch elementli» deyiladi (052-2009, 2.2)"},
      {"savol": "Yon rama va nadressor balkasi qaysi po'latdan tayyorlanadi?", "variantlar": ["Ст3 ГОСТ 380", "20ГЛ, 20ГФЛ, 20ГТЛ ГОСТ 32400", "55С2 ГОСТ 14959", "40Х ГОСТ 4543"], "togri": 1, "izoh": "052-2009, band 2.4"},
      {"savol": "Ressor komplekti prujinasi qaysi po'latdan tayyorlanadi?", "variantlar": ["55С2, 60С2, 55С2А va shu kabilar ГОСТ 14959", "15Л", "20ГЛ", "Ст3 сп"], "togri": 0, "izoh": "052-2009, band 2.4"},
      {"savol": "Shkvoren qaysi materialdan tayyorlanadi?", "variantlar": ["Ст 3 сп ГОСТ 380 yoki ГОСТ 1050 bo'yicha po'lat", "55РП", "20ХГСА", "СЧ 35"], "togri": 0, "izoh": "052-2009, band 2.4"},
      {"savol": "Elektropayvand bilan qotiriladigan yeyilishga chidamli kontakt elementlari qanday qattiqlikka termik ishlanadi?", "variantlar": ["240…300 HB", "320…400 HB", "200…240 HB", "270…370 HB"], "togri": 3, "izoh": "20ХГСА ГОСТ 4543, 270…370 HB (052-2009, band 2.4)"},
      {"savol": "Elektropayvandsiz qotiriladigan yeyilishga chidamli kontakt elementlari qanday qattiqlikka ishlanadi?", "variantlar": ["320…400 HB", "180…220 HB", "240…300 HB", "270…370 HB"], "togri": 0, "izoh": "30ХГСА ГОСТ 11269, 320…400 HB (052-2009, band 2.4)"},
      {"savol": "Tip 2 aravachaning konstruktiv harakat tezligi qancha?", "variantlar": ["110 km/soat", "100 km/soat", "140 km/soat", "120 km/soat"], "togri": 3, "izoh": "052-2009, 2.1-jadval"},
      {"savol": "Tip 2 ikki o'qli aravachaning massasi qancha?", "variantlar": ["5 t dan ko'p emas", "3 t dan ko'p emas", "8 t dan ko'p emas", "12,0 t"], "togri": 0, "izoh": "052-2009, 2.1-jadval; 18-101 modeli uchun esa 12,0 t"},
      {"savol": "18-101 modeli to'rt o'qli aravachaning massasi qancha?", "variantlar": ["8 t", "5 t", "10 t", "12,0 t"], "togri": 3, "izoh": "052-2009, 2.1-jadval"},
      {"savol": "Tip 2 aravachaning ramasi qanday turda?", "variantlar": ["Bog'lanmagan (без связевая)", "Bog'langan (связевая)", "Payvandlangan", "Boltli"], "togri": 0, "izoh": "052-2009, 2.1-jadval. 18-101 modelida esa bog'langan"},
      {"savol": "Friksion so'ndirgich qanday vazifani bajaradi?", "variantlar": ["Vagon og'irligini uzatadi", "Tebranish energiyasini ishqalanish orqali issiqlikka aylantiradi", "G'ildirakni yo'naltiradi", "Tormoz kuchini oshiradi"], "togri": 1, "izoh": "Nadressor balkasi prizmasi, friksion pona va friksion planka orasidagi ishqalanish"},
      {"savol": "Prizmaning qiya yuzasi gorizontalga nisbatan qaysi burchak ostida joylashgan?", "variantlar": ["45°", "30°", "60°", "75°"], "togri": 0, "izoh": "050-2020, band 5.1.1"},
      {"savol": "Depo ta'miri (ДР) bilan kapital ta'mir (КР) orasidagi asosiy farq nimada?", "variantlar": ["Farq yo'q", "ДР da detal almashtiriladi", "КР da yeyilgan yuzalar chizma o'lchamigacha tiklanadi", "ДР faqat bo'yash"], "togri": 2, "izoh": "052-2009, 6.1-jadval va 9.5-band"},
      {"savol": "Ta'mir me'yorlarining o'zi qaysi hujjatda belgilangan?", "variantlar": ["РД 32 ЦВ 052-2009 «Rahbariyat»", "ГОСТ 9246-2013", "РД 32 ЦВ 050-2020", "ПР НК В.3"], "togri": 0, "izoh": "050-2020 o'lchash usulini beradi, me'yorlar esa Rahbariyatda"},
      {"savol": "РД 32 ЦВ 050-2020 nimani belgilaydi?", "variantlar": ["Parametrlarni o'lchash metodikasini", "Vagon konstruksiyasini", "Bo'yash tartibini", "Ta'mir texnologiyasini"], "togri": 0, "izoh": "050-2020, band 1.1"},
      {"savol": "G'ildirak juftlari parametrlari qaysi hujjat bo'yicha nazorat qilinadi?", "variantlar": ["732-ЦВ-ЦЛ", "РД 32 ЦВ 050-2020", "РД ВНИИЖТ 27.05.01-2017 va РД 32 ЦВ 058-2019", "ПР НК В.3"], "togri": 2, "izoh": "050-2020, band 4.2"},
      {"savol": "Pyatnik–podpyatnik uzeli qaysi hujjat bo'yicha nazorat qilinadi?", "variantlar": ["РД 32 ЦВ 067-2008", "ГОСТ 1452-2011", "РД 32 ЦВ 064-2020", "РД 32 ЦВ 058-2019"], "togri": 0, "izoh": "050-2020, band 4.5"},
      {"savol": "Aravacha ta'mirlash huquqini olish uchun imtihon qanchalik tez-tez topshiriladi?", "variantlar": ["Har besh yilda", "Har yili", "Bir marta, ishga kirishda", "Har uch yilda"], "togri": 1, "izoh": "052-2009, band 3.2 — tekshiruv imtihonlari har yili o'tkaziladi"},
      {"savol": "Nadressor balkasining ustida nima joylashgan?", "variantlar": ["Friksion ponalar", "Triangellar", "Podpyatnik va ikkita yon skolzun", "Buksa proyomlari"], "togri": 2, "izoh": "052-2009, band 2.2"},
      {"savol": "Yeyilishga chidamli yechiladigan elementlar qaysi loyihalar bo'yicha o'rnatiladi?", "variantlar": ["Har qanday loyiha", "Faqat С 03.04", "М 1698 ПКБ ЦВ, С 03.04 yoki 1699.00.000", "Faqat М 1698 ПКБ ЦВ"], "togri": 2, "izoh": "052-2009, band 2.2; aralash o'rnatish taqiqlanadi (14.9)"},
    ],
  },
  {
    nom: "O'lchov vositalari va shablonlar",
    daraja: "Boshlang'ich",
    tavsif: "Qaysi parametr qaysi shablon bilan o'lchanadi, ularning belgilari va shartlari.",
    savollar: [
      {"savol": "Nadressor balkasi prizmasi qiya yuzalarining burchagi qaysi shablon bilan nazorat qilinadi?", "variantlar": ["Т914.007", "НП Т914.05.000", "Т914.009", "Т914.09.000"], "togri": 1, "izoh": "050-2020, band 5.1.1"},
      {"savol": "Shablon НП ning bazaviy o'lchami qancha?", "variantlar": ["160,0 mm", "185,0 mm", "175,5 mm", "166,0 mm"], "togri": 2, "izoh": "050-2020, 1-rasm"},
      {"savol": "Shablon НП da 1-pozitsiya nima deb ataladi?", "variantlar": ["Oyoqcha", "Dvijok", "Polzunok", "Nakladka"], "togri": 2, "izoh": "050-2020, 1-rasm: 1 — polzunok, 2 — oyoqchalar, 3 — nakladka, 4 — dvijok"},
      {"savol": "Friksion pona uchun cheklovchi burtlar orasidagi «e» masofasi qaysi shablon bilan o'lchanadi?", "variantlar": ["Т1354.000", "Т914.007", "Т914.009", "Т914.05.000"], "togri": 1, "izoh": "050-2020, band 5.1.4; ТУ 32 ЦВ 2023-2000"},
      {"savol": "Buksa proyomi kengligi qaysi shablon bilan nazorat qilinadi?", "variantlar": ["Т914.007", "Т914.01.000", "Т914.009", "Т914.02.000"], "togri": 2, "izoh": "050-2020, band 5.2.1; ТУ 32 ЦВ 2504-2000"},
      {"savol": "Yon ramaning bazaviy o'lchami «М» qaysi asbob bilan o'lchanadi?", "variantlar": ["Shtangen Т914.01.000", "Shtangen Н Т914.03.000", "Shtangen ФП Т914.02.000", "Shablon Т914.009"], "togri": 0, "izoh": "050-2020, band 5.2.4; ТУ 32 ЦВ 2018-95"},
      {"savol": "Friksion plankalar orasidagi o'lcham qaysi asbob bilan o'lchanadi?", "variantlar": ["ШЦ-II-250-800", "Т914.009", "Shtangen ФП Т914.02.000", "Shtangen Н Т914.03.000"], "togri": 2, "izoh": "050-2020, band 5.2.5; ТУ 32 ЦВ 2019-95"},
      {"savol": "«H₁ − H₂» farqi qaysi asbob bilan aniqlanadi?", "variantlar": ["Shtangen ФП", "Shtangen Н Т914.03.000", "Shtangen М", "Kronsirkul"], "togri": 1, "izoh": "050-2020, band 5.2.7; ТУ 32 ЦВ 2020-95"},
      {"savol": "Prizmalar yo'naltiruvchi burtlarining nosimmetrikligi qaysi moslama bilan aniqlanadi?", "variantlar": ["Т914.18.000", "Т1354.000", "Т914.22.000", "Т914.21.000"], "togri": 1, "izoh": "050-2020, band 5.1.5 — moslama Т1354.000 va 1000 mm chizg'ich"},
      {"savol": "Friksion ponaning yeyilishi qaysi shablon bilan o'lchanadi?", "variantlar": ["Т914.05.000", "Т914.09.000", "Т914.007", "Т914.18.000"], "togri": 1, "izoh": "050-2020, band 5.3.2; ТУ 32 ЦВ 2430-96"},
      {"savol": "Ponalarning nadressor balkasiga nisbatan holati qaysi moslama bilan tekshiriladi?", "variantlar": ["Т914.09.000", "Т914.21.000", "Т914.18.000", "Т1354.000"], "togri": 2, "izoh": "050-2020, band 5.5"},
      {"savol": "Yon rama yo'naltiruvchilari bilan buksa korpusi orasidagi zazorlar qaysi moslama bilan o'lchanadi?", "variantlar": ["Т914.22.000", "Т914.21.000", "Т914.23.000", "Т914.18.000"], "togri": 1, "izoh": "050-2020, band 5.2.13"},
      {"savol": "Tashqi prujinaning ichki diametri qaysi kalibr bilan tekshiriladi?", "variantlar": ["Т914.22.000 (stakan-probka)", "ШГ-300-0,1", "Т914.21.000", "Т914.23.000 (kalibr-stakan)"], "togri": 0, "izoh": "050-2020, band 5.4.3"},
      {"savol": "Prujinaning erkin holatdagi balandligi qaysi asbob bilan o'lchanadi?", "variantlar": ["Kronsirkul", "Shtangenglubinomer ШГ-300-0,1 ГОСТ 162", "Chizg'ich 300 mm", "Shtangensirkul ШЦ-I-125"], "togri": 1, "izoh": "050-2020, band 5.4.2 — plita ГОСТ 10905 ustida"},
      {"savol": "Yoriqlarni vizual aniqlashda lupaning kattalashtirish darajasi qanday bo'lishi kerak?", "variantlar": ["Kamida to'rt karra", "Kamida uch karra", "Kamida ikki karra", "Kamida o'n karra"], "togri": 0, "izoh": "Лупа ЛП-1-4 ГОСТ 25706, kamida 4 karra (050-2020, 5.3.1)"},
      {"savol": "O'lchash paytida obyekt va ish maydoni harorati farqi qancha bo'lishi mumkin?", "variantlar": ["±5 °C", "±10 °C", "Cheklov yo'q", "±2 °C"], "togri": 0, "izoh": "050-2020, band 3.2"},
      {"savol": "Metodikada ko'rsatilmagan boshqa o'lchov vositasidan foydalanish mumkinmi?", "variantlar": ["Faqat kapital ta'mirda", "Ha, agar kerakli aniqlikni bersa va qo'llashga ruxsat etilgan bo'lsa", "Faqat ustaning ruxsati bilan", "Yo'q, taqiqlanadi"], "togri": 1, "izoh": "050-2020, band 3.4"},
      {"savol": "Shchuplar to'plamini almashtirishda qanday shart bor?", "variantlar": ["Cheklov yo'q", "Dopusk 0,5 mm gacha", "Faqat Т914.21.000 ishlatiladi", "Tayyorlash dopuski 0,05 mm dan oshmasin"], "togri": 3, "izoh": "050-2020, band 5.1.6"},
      {"savol": "Naplavka qattiqligi qanday asbob bilan o'lchanadi?", "variantlar": ["Shtangensirkul", "Dinamik qattiqlik o'lchagich (ТЭМП 3 tipidagi)", "Kalibr", "Shablon"], "togri": 1, "izoh": "050-2020, 5.1.7; 052-2009, 6.5 — ГОСТ 9012-59, ГОСТ 9013-59"},
      {"savol": "Aravachalar ta'mir uchastkasiga qanday holatda keladi?", "variantlar": ["Bo'yalgan holda", "Qismlarga ajratilgan holda", "Tozalangan va g'ildirak juftlarisiz yuvilgan holda", "G'ildirak juftlari bilan birga"], "togri": 2, "izoh": "050-2020, band 3.1"},
    ],
  },
  {
    nom: "Nadressor balkasi — o'lchamlar",
    daraja: "O'rta",
    tavsif: "45° burchak dopuski, «З» o'lchami, qolgan qalinlik, burtlar, skolzun va podpyatnik.",
    savollar: [
      {"savol": "45° burchak dopuskini o'lchashda K₁ qanday hisoblanadi?", "variantlar": ["C₁past + C₁yuqori", "C₁past × 1,41", "|C₁past − C₁yuqori|", "175,5 − C₁past"], "togri": 2, "izoh": "050-2020, formula (1)"},
      {"savol": "K₁ va K₂ qiymatlari qanday bo'lishi kerak?", "variantlar": ["10 mm dan kichik", "3 mm dan kichik", "6 mm dan kichik", "1 mm dan kichik"], "togri": 1, "izoh": "050-2020, formulalar (1) va (2)"},
      {"savol": "45° burchak dopuski — pastdagi umumiy tirqish qancha bo'lishi mumkin?", "variantlar": ["6,0 mm dan ko'p emas", "10,0 mm dan ko'p emas", "2,0 mm dan ko'p emas", "3,0 mm dan ko'p emas"], "togri": 0, "izoh": "050-2020, 1-jadval, band 5.1.1"},
      {"savol": "Burchak dopuskini o'lchash burt chetidan qancha masofada bajariladi?", "variantlar": ["5…10 mm", "15…30 mm", "30…50 mm", "10…15 mm"], "togri": 1, "izoh": "050-2020, band 5.1.1 — ikkita kesimda"},
      {"savol": "Dvijok ko'rsatkichi «0» dan o'ngda bo'lsa, qanday ishora qo'yiladi?", "variantlar": ["Ishora qo'yilmaydi", "«+»", "«±»", "«−»"], "togri": 3, "izoh": "050-2020, band 5.1.1 — o'ngda minus, chapda plyus"},
      {"savol": "«З» o'lchami qaysi formula bo'yicha hisoblanadi?", "variantlar": ["З = 175,5 + (1,41 × K)", "З = 166 + K", "З = 175,5 − K", "З = 175,5 × 1,41"], "togri": 0, "izoh": "050-2020, formula (3)"},
      {"savol": "Formuladagi 1,41 koeffitsienti nimadan kelib chiqadi?", "variantlar": ["Shablon uzunligidan", "Metall kengayishidan", "Prujina qattiqligidan", "45° burchakdan (√2 ning taqribiy qiymati)"], "togri": 3, "izoh": "050-2020, band 5.1.2"},
      {"savol": "«K» = −4 mm bo'lsa, «З» nechchi?", "variantlar": ["170 mm", "166 mm", "168 mm", "173 mm"], "togri": 0, "izoh": "175,5 + 1,41×(−4) = 169,9 ≈ 170 mm (050-2020, 2-jadval)"},
      {"savol": "«K» = −7 bo'lsa, «З» nechchi?", "variantlar": ["167 mm", "168 mm", "171 mm", "166 mm"], "togri": 3, "izoh": "050-2020, 2-jadval"},
      {"savol": "«K» = +2 bo'lsa, «З» nechchi?", "variantlar": ["178 mm", "177 mm", "175,5 mm", "179 mm"], "togri": 0, "izoh": "050-2020, 2-jadval"},
      {"savol": "Depo ta'miridan chiqarishda «З» ning eng kichik qiymati qancha?", "variantlar": ["175,0 mm", "160,0 mm", "166,0 mm", "170,0 mm"], "togri": 2, "izoh": "050-2020, band 5.1.2; 052-2009, 9.1-jadval"},
      {"savol": "Nadressor balkasi qiya yuzasining qolgan qalinligi kamida qancha bo'lishi kerak?", "variantlar": ["10 mm", "7 mm", "18 mm", "5 mm"], "togri": 1, "izoh": "050-2020, band 5.1.3 (Rahbariyat 9.5.2)"},
      {"savol": "Ultratovush nazoratida nechta zonada o'lchanadi?", "variantlar": ["Ikkita", "Uchta", "Oltita", "To'rtta"], "togri": 3, "izoh": "050-2020, 5-rasm"},
      {"savol": "1-zonada natija h_min dan kichik chiqsa nima qilinadi?", "variantlar": ["Boshqa asbob ishlatiladi", "O'lchash takrorlanmaydi", "Qo'shni ikkita nuqtada qo'shimcha o'lchanib, uchtasining o'rtachasi olinadi", "Balka darrov brak qilinadi"], "togri": 2, "izoh": "050-2020, band 5.1.3"},
      {"savol": "Depo ta'mirida cheklovchi burtlar orasidagi «e» masofasi qancha bo'lishi mumkin?", "variantlar": ["138 mm", "134 mm", "144,0 mm dan ko'p emas", "150 mm dan ko'p emas"], "togri": 2, "izoh": "050-2020, band 5.1.4; 052-2009, 9.1-jadval"},
      {"savol": "Kapital ta'mirda «e» masofasi qancha bo'lishi kerak?", "variantlar": ["140 (+4) mm", "134 ± 1 mm", "134 (+4) mm", "144 (+4) mm"], "togri": 2, "izoh": "052-2009, 9.1-jadval"},
      {"savol": "Prizmalar yo'naltiruvchi burtlarining nosimmetrikligi |A₁ − A₂| qancha bo'lishi mumkin?", "variantlar": ["10 mm dan ko'p emas", "2 mm dan ko'p emas", "5 mm dan ko'p emas", "3 mm dan ko'p emas"], "togri": 2, "izoh": "050-2020, band 5.1.5"},
      {"savol": "Skolzun qalpog'ining notekis yeyilishi «Р» depo ta'mirida qancha bo'lishi mumkin?", "variantlar": ["3 mm dan ko'p emas", "1 mm", "2 mm dan ko'p emas", "5 mm dan ko'p emas"], "togri": 2, "izoh": "050-2020, band 5.1.6"},
      {"savol": "Skolzun qalpog'i necha diagonal bo'yicha tekshiriladi?", "variantlar": ["Bitta", "Ikkita", "To'rtta", "Uchta"], "togri": 1, "izoh": "050-2020, band 5.1.6"},
      {"savol": "Yeyilishga chidamli yuzalar naplavkasining qattiqligi qanday bo'lishi kerak?", "variantlar": ["270…370 HB", "240…300 HB", "180…220 HB", "320…400 HB"], "togri": 1, "izoh": "050-2020, band 5.1.7 (Rahbariyat 9.5.1)"},
    ],
  },
  {
    nom: "Yon rama — o'lchamlar",
    daraja: "O'rta",
    tavsif: "Buksa proyomi, yo'naltiruvchilar, bazaviy o'lcham «М» va friksion plankalar.",
    savollar: [
      {"savol": "Yon rama bo'yicha o'lchashlar qaysi balandlikda bajariladi?", "variantlar": ["Ramaning pastidan 60 mm", "Ramaning pastidan 40 mm", "Ramaning pastidan 100 mm", "O'rtada"], "togri": 0, "izoh": "050-2020, bandlar 5.2.1, 5.2.4, 5.2.7"},
      {"savol": "Kapital ta'mirda buksa proyomi kengligi «a» qancha bo'lishi kerak?", "variantlar": ["330 ± 1 mm", "342 ± 1 mm", "335 ± 1 mm", "338 ± 1 mm"], "togri": 2, "izoh": "050-2020, band 5.2.1; 052-2009, 8.1-jadval"},
      {"savol": "Depo ta'mirida buksa proyomi kengligi qancha bo'lishi mumkin (umumiy holda)?", "variantlar": ["350 mm dan ko'p emas", "338 mm dan ko'p emas", "342,0 mm dan ko'p emas", "335 mm dan ko'p emas"], "togri": 2, "izoh": "050-2020, band 5.2.1"},
      {"savol": "Buksa proyomi yo'naltiruvchilarining kengligi «В» chizma bo'yicha qancha?", "variantlar": ["160 ± 1 mm", "155 ± 1 mm", "165 ± 1 mm", "150 ± 1 mm"], "togri": 0, "izoh": "050-2020, band 5.2.3; 052-2009, 8.1-jadval"},
      {"savol": "Depo ta'miridan chiqarishda «В» ning eng kichik qiymati qancha (umumiy holda)?", "variantlar": ["154 mm", "155 mm", "160 mm", "150 mm"], "togri": 1, "izoh": "050-2020, band 5.2.3"},
      {"savol": "«В» nima uchun bir necha balandlikda o'lchanadi?", "variantlar": ["Konussimon yeyilishni aniqlash uchun", "Shablon shunday", "Talab yo'q", "Vaqtni tejash uchun"], "togri": 0, "izoh": "050-2020, band 5.2.3 — ishchi yuzaning butun balandligi bo'yicha"},
      {"savol": "Yon ramaning bazaviy o'lchami «М» chizma bo'yicha qancha?", "variantlar": ["2185 (+7/−5) mm", "2200 (+7/−5) mm", "2190 (+7/−5) mm", "2185 ± 5 mm"], "togri": 0, "izoh": "050-2020, band 5.2.4; 052-2009, 8.1-jadval"},
      {"savol": "Depo ta'miridan chiqarishda «М» qancha bo'lishi mumkin?", "variantlar": ["2185 mm dan ko'p emas", "2210 mm dan ko'p emas", "2192 mm dan ko'p emas", "2200,0 mm dan ko'p emas"], "togri": 3, "izoh": "050-2020, band 5.2.4"},
      {"savol": "Bitta aravachadagi ikkita yon rama bazalari farqi qancha bo'lishi mumkin?", "variantlar": ["1 mm dan ko'p emas", "2 mm dan ko'p emas", "5 mm dan ko'p emas", "3 mm dan ko'p emas"], "togri": 1, "izoh": "052-2009, bandlar 6.10, 8.15, 18.11"},
      {"savol": "Buksa proyomi tayanch yuzasidagi kanavkasimon yeyilishning ruxsat etilgan chuqurligi?", "variantlar": ["2 mm dan ko'p emas", "3 mm dan ko'p emas", "5 mm dan ko'p emas", "1 mm dan ko'p emas"], "togri": 0, "izoh": "050-2020, band 5.2.2; 052-2009, 8.3"},
      {"savol": "Kanavkasimon yeyilishning ruxsat etilgan kengligi?", "variantlar": ["20 mm dan ko'p emas", "15 mm dan ko'p emas", "30 mm dan ko'p emas", "10 mm dan ko'p emas"], "togri": 0, "izoh": "050-2020, band 5.2.2"},
      {"savol": "Friksion plankalar orasidagi «L₁» o'lchami planka qalinligi 10 mm bo'lganda qancha?", "variantlar": ["642 mm dan kam emas", "630 mm dan kam emas", "648 mm dan kam emas", "668 mm dan kam emas"], "togri": 0, "izoh": "050-2020, band 5.2.5"},
      {"savol": "Planka qalinligi 16 mm bo'lganda «L₁» qancha?", "variantlar": ["642 mm dan kam emas", "648 mm dan kam emas", "630 mm dan kam emas", "620 mm dan kam emas"], "togri": 2, "izoh": "050-2020, band 5.2.5"},
      {"savol": "Friksion plankalarning pastga kengayishi qanday oraliqda bo'lishi kerak?", "variantlar": ["10…16 mm", "4…10 mm", "5…12 mm", "2…5 mm"], "togri": 1, "izoh": "050-2020, band 5.2.5 — kengayish = L₂ − L₁"},
      {"savol": "Plankalarning gorizontal tekislikdagi noparallelligi qancha bo'lishi mumkin?", "variantlar": ["1 mm dan ko'p emas", "2 mm dan ko'p emas", "5 mm dan ko'p emas", "3,0 mm dan ko'p emas"], "togri": 3, "izoh": "050-2020, band 5.2.5"},
      {"savol": "Qo'zg'almas friksion planka (10 mm) yeyilishi qancha bo'lishi mumkin?", "variantlar": ["1,0 mm", "1,5 mm dan ko'p emas", "3,0 mm dan ko'p emas", "2,0 mm dan ko'p emas"], "togri": 1, "izoh": "050-2020, band 5.2.6; 052-2009, 18.7"},
      {"savol": "Harakatlanuvchi plankalarning qalinlik bo'yicha umumiy yeyilishi qancha?", "variantlar": ["2,0 mm dan ko'p emas, bir tomondan 1,5 mm dan ko'p emas", "1,5 mm dan ko'p emas", "3,0 mm dan ko'p emas", "Cheklov yo'q"], "togri": 0, "izoh": "050-2020, band 5.2.6"},
      {"savol": "«H₁ − H₂» farqi qancha bo'lishi mumkin?", "variantlar": ["1 mm dan ko'p emas", "2 mm dan ko'p emas", "5 mm dan ko'p emas", "3,0 mm dan ko'p emas"], "togri": 3, "izoh": "050-2020, band 5.2.7"},
      {"savol": "«H₁ − H₂» ni o'lchashda qanday shart bajarilishi kerak?", "variantlar": ["Friksion plankalar olib tashlangan bo'lishi", "Prujinalar o'rnatilgan bo'lishi", "Vagon ostida bo'lishi", "Aravacha yig'ilgan bo'lishi"], "togri": 0, "izoh": "050-2020, band 5.2.7"},
      {"savol": "Klepka ishlaridan oldin privalochniy yuzalar orasidagi proyom o'lchami qancha bo'lishi kerak?", "variantlar": ["668 (−3) mm", "672 (−3) mm", "660 (−3) mm", "648 (−3) mm"], "togri": 0, "izoh": "050-2020, band 5.2.9"},
    ],
  },
  {
    nom: "Friksion pona, prujinalar va zazorlar",
    daraja: "O'rta",
    tavsif: "Pona yeyilishi, yangi pona o'lchamlari, ressor komplekti va buksa zazorlari.",
    savollar: [
      {"savol": "Ponaning vertikal tekisligi yeyilishini o'lchaganda natijadan nima qilinadi?", "variantlar": ["2 mm ayiriladi", "Hech nima", "2 mm qo'shiladi", "Chizg'ich qalinligi qo'shiladi"], "togri": 0, "izoh": "050-2020, band 5.3.2 — nominal to'liqlik o'lchamiga keltirish"},
      {"savol": "Ponaning qiya tekisligi yeyilishini o'lchaganda natijaga nima qilinadi?", "variantlar": ["2 mm ayiriladi", "Chizg'ich qalinligi «Y» qo'shiladi", "1,41 ga ko'paytiriladi", "Hech nima"], "togri": 1, "izoh": "050-2020, band 5.3.2"},
      {"savol": "Depo ta'mirida ponaning umumiy yeyilishi qancha bo'lishi mumkin?", "variantlar": ["2 mm dan ko'p emas", "3,0 mm dan ko'p emas, bir tomondan 2,0 mm dan ko'p emas", "Cheklov yo'q", "5 mm dan ko'p emas"], "togri": 1, "izoh": "050-2020, band 5.3.2; 052-2009, 6.1-jadval"},
      {"savol": "Kapital ta'mirda friksion ponalar bilan nima qilinadi?", "variantlar": ["O'lchanadi va qoldiriladi", "Naplavka qilinadi", "Yangisiga almashtiriladi", "Payvandlanadi"], "togri": 2, "izoh": "052-2009, 6.1-jadval — «новый»"},
      {"savol": "Nazorat boshlanishidan oldin ponada nima belgilanadi?", "variantlar": ["Qiya yuza o'lchami «X» va uning o'rtasi «X/2»", "Tayyorlangan yili", "Chizmа raqami", "Og'irligi"], "togri": 0, "izoh": "050-2020, band 5.3.2"},
      {"savol": "Friksion ponadagi yoriqlar qayerda ruxsat etilmaydi?", "variantlar": ["Qattiqlik qovurg'alarida", "Faqat qiya yuzada", "Hech qayerda ruxsat etilmaydi", "Faqat asosda"], "togri": 0, "izoh": "050-2020, band 5.3.1"},
      {"savol": "Upor burt uzunligi «С» M1698.00.003 chizmasi bo'yicha kamida qancha?", "variantlar": ["67 mm", "60 mm", "66 mm", "69 mm"], "togri": 2, "izoh": "050-2020, band 5.3.2"},
      {"savol": "Upor burt uzunligi «С» 100.30.001-1 chizmasi bo'yicha kamida qancha?", "variantlar": ["71 mm", "66 mm", "67 mm", "69 mm"], "togri": 2, "izoh": "050-2020, band 5.3.2"},
      {"savol": "Yangi ponaning asos uzunligi «В» qancha bo'lishi kerak?", "variantlar": ["130 ± 2 mm", "212 ± 2 mm", "249 ± 2 mm", "175 ± 2 mm"], "togri": 1, "izoh": "050-2020, band 5.3.3"},
      {"savol": "Yangi ponaning qiya tekislik kengligi «D» qancha?", "variantlar": ["150 ± 2 mm", "140 ± 2 mm", "130 ± 2 mm", "120 ± 2 mm"], "togri": 2, "izoh": "050-2020, band 5.3.3"},
      {"savol": "Yangi ponaning qiya tekislikdagi o'yiq chuqurligi «Z» qancha?", "variantlar": ["1 ± 1 mm", "5 ± 1 mm", "2 ± 1 mm", "3 ± 1 mm"], "togri": 2, "izoh": "050-2020, band 5.3.3"},
      {"savol": "Yangi ponada «С» o'lchami СЧ 35 chizmalari uchun qancha?", "variantlar": ["66 ± 1 mm", "69 ± 1 mm", "71 ± 2 mm", "67 ± 1 mm"], "togri": 1, "izoh": "050-2020, 3-jadval"},
      {"savol": "Yangi ponada «С» o'lchami Сталь 20Л chizmalari uchun qancha?", "variantlar": ["69 ± 1 mm", "73 ± 2 mm", "66 ± 1 mm", "71 ± 2 mm"], "togri": 3, "izoh": "050-2020, 3-jadval"},
      {"savol": "Prujinaning erkin holatdagi balandligi umumiy holda qancha?", "variantlar": ["249 (+7/−2) mm", "249 (+6/−3) mm", "240 (+6/−3) mm", "255 (+6/−3) mm"], "togri": 1, "izoh": "050-2020, band 5.4.2"},
      {"savol": "18-100 va 18-101 modellari uchun 1989–2012-yillarda tayyorlangan prujina balandligi?", "variantlar": ["249 (+6/−2) mm", "249 (+7/−2) mm", "249 (+6/−3) mm", "249 ± 3 mm"], "togri": 1, "izoh": "050-2020, band 5.4.2"},
      {"savol": "Komplektga prujinalarni tanlashda balandlik farqi qancha bo'lishi mumkin?", "variantlar": ["4 mm dan oshmasin", "10 mm", "2 mm", "6 mm"], "togri": 0, "izoh": "050-2020, band 5.4.2 (Rahbariyat 11.3)"},
      {"savol": "Kalibr prujinaga qanday kiritiladi?", "variantlar": ["Aylantirib", "O'z og'irligi ostida erkin o'tishi kerak", "Kuch bilan bosib", "Bolg'a bilan urib"], "togri": 1, "izoh": "050-2020, band 5.4.3"},
      {"savol": "Tashqi/ichki prujina prutogining umumiy diametri qancha?", "variantlar": ["27/18 mm", "29/20 mm", "30/21 mm", "32/22 mm"], "togri": 1, "izoh": "050-2020, band 5.4.4; 18-9597 uchun 30/21 mm"},
      {"savol": "Prujinalarning tayanch yuzalari qanday ishlangan bo'lishi kerak?", "variantlar": ["Ishlanmaydi", "O'ram uchidan aylananing 0,7…0,8 yoyi bo'yicha mexanik ishlangan", "Butun o'ram bo'yicha", "Faqat bo'yaladi"], "togri": 1, "izoh": "ГОСТ 1452-2011, band 4.6.3"},
      {"savol": "Prujinalarda qanday nuqson ruxsat etilmaydi?", "variantlar": ["Chang", "Yengil zang", "Bo'yoq izlari", "O'ram kesimi maydonining 10% dan ortiq korroziyasi"], "togri": 3, "izoh": "050-2020, band 5.4.1"},
    ],
  },
  {
    nom: "Aravachani ajratish va defektatsiya",
    daraja: "O'rta",
    tavsif: "Ajratish ketma-ketligi, brak mezonlari, 6.1-jadval o'lchamlari.",
    savollar: [
      {"savol": "Ikki o'qli aravachani ajratish qayerdan boshlanadi?", "variantlar": ["Ta'mir pozitsiyasida", "Bo'yash kamerasida", "Vagon ostida", "Yuvish mashinasi oldida — rama g'ildirak juftlaridan olinadi"], "togri": 3, "izoh": "052-2009, band 5.1"},
      {"savol": "Nadressor balkasini ko'tarishdan oldin nima chiqariladi?", "variantlar": ["Prujinalar", "Friksion ponalar", "Shkvoren", "Triangellar"], "togri": 2, "izoh": "052-2009, band 5.2"},
      {"savol": "Yechilgan shplintlar bilan nima qilinadi?", "variantlar": ["Payvandlanadi", "Qayta ishlatiladi", "Yangi tipik shplintlarga almashtiriladi", "To'g'rilanadi"], "togri": 2, "izoh": "052-2009, band 6.7"},
      {"savol": "Yig'uvda shplint uchlari qanday burchak ostida yoyiladi?", "variantlar": ["90°", "180°", "60°", "45°"], "togri": 0, "izoh": "052-2009, band 14.2"},
      {"savol": "Defektatsiya buzmasdan nazoratdan (НК) oldin bajariladimi?", "variantlar": ["Bir vaqtda", "Yo'q, keyin", "Ha, oldin — Ж ilovasiga muvofiq", "Talab yo'q"], "togri": 2, "izoh": "052-2009, band 6.1"},
      {"savol": "Defektatsiya qanday usullarda o'tkaziladi?", "variantlar": ["Faqat instrumental", "Vizual va instrumental", "Faqat defektoskop bilan", "Faqat vizual"], "togri": 1, "izoh": "052-2009, band 6.2"},
      {"savol": "1986-yildan keyin tayyorlangan balkaning podpyatnik chuqurligi qancha bo'lishi kerak?", "variantlar": ["47,5 mm", "36 (+1/−2) mm", "25 (+1/−2) mm", "30 (+1/−2) mm"], "togri": 3, "izoh": "052-2009, 6.1-jadval"},
      {"savol": "1986-yilgacha tayyorlangan balkaning podpyatnik chuqurligi qancha?", "variantlar": ["36 (+1/−2) mm", "30 (+1/−2) mm", "18 mm", "25 (+1/−2) mm"], "togri": 3, "izoh": "052-2009, 6.1-jadval"},
      {"savol": "Nadressor balkasi podpyatnigining 10 mm chuqurlikdagi diametri qancha?", "variantlar": ["310 (+1,5) mm", "457 (+1/−2) mm", "302,5 (+1,5) mm", "298 (−1,3) mm"], "togri": 2, "izoh": "052-2009, 6.1-jadval, konusligi 1:12,5"},
      {"savol": "Podpyatnik tayanch yuzasining qolgan qalinligi kamida qancha bo'lishi kerak?", "variantlar": ["7 mm", "10 mm", "25 mm", "18 mm"], "togri": 3, "izoh": "052-2009, band 9.4.5"},
      {"savol": "Depo ta'mirida shkvorenning diametri bo'yicha yeyilishi qancha bo'lishi mumkin?", "variantlar": ["2 mm", "3 mm dan ko'p emas", "1 mm", "5 mm dan ko'p emas"], "togri": 1, "izoh": "052-2009, band 6.9"},
      {"savol": "Kapital ta'mirda shkvorenning yeyilishiga ruxsat beriladimi?", "variantlar": ["Ha, 3 mm gacha", "Ha, 5 mm gacha", "Faqat 1 mm gacha", "Yo'q, ruxsat etilmaydi"], "togri": 3, "izoh": "052-2009, band 6.9"},
      {"savol": "Shkvorenning uzunligi qancha bo'lishi kerak?", "variantlar": ["400 ± 3 mm", "420 ± 3 mm", "440 ± 3 mm", "460 ± 3 mm"], "togri": 2, "izoh": "052-2009, band 9.7"},
      {"savol": "Egilishi qancha bo'lgan shkvorenni depo ta'mirida to'g'rilashga ruxsat beriladi?", "variantlar": ["5 mm dan ko'p bo'lmagan", "3 mm gacha", "2 mm gacha", "10 mm gacha"], "togri": 0, "izoh": "052-2009, band 9.8 — qizdirilgan holatda"},
      {"savol": "Yoriqlari yoki 5 mm dan ortiq egilishi bor shkvoren bilan nima qilinadi?", "variantlar": ["Almashtirishga tegishli", "To'g'rilanadi", "Naplavka qilinadi", "Payvandlanadi"], "togri": 0, "izoh": "052-2009, band 6.9"},
      {"savol": "Aravachaning barcha tarkibiy qismlarida yoriqlar bo'yicha asosiy qoida qanday?", "variantlar": ["Barcha yoriqlar payvandlanadi", "Ruxsat etilmaydi, rejali ta'mirda bartaraf etiladiganlaridan tashqari", "Faqat uzun yoriqlar brak", "Yoriq muhim emas"], "togri": 1, "izoh": "052-2009, band 6.3"},
      {"savol": "Yeyilishi me'yordan ortiq quyma detallar bilan nima qilinadi?", "variantlar": ["Faqat bo'yaladi", "Payvand va naplavka bilan ta'mirlanib, chizma o'lchamigacha mexanik ishlanadi", "Darrov brak", "O'z holicha qoldiriladi"], "togri": 1, "izoh": "052-2009, band 6.5"},
      {"savol": "Depo ta'mirida polimer vtulkalarni qayta ishlatish mumkinmi?", "variantlar": ["Faqat kapital ta'mirda", "Ha, yoriq va yirtiq bo'lmasa va yaroqlilik muddati tugamasa", "Har doim", "Yo'q"], "togri": 1, "izoh": "052-2009, band 6.8"},
      {"savol": "Skolzun qalpog'ida yoriq yoki sinish bo'lsa nima qilinadi?", "variantlar": ["Naplavka qilinadi", "Brak qilinadi", "Payvandlanadi", "Qoldiriladi"], "togri": 1, "izoh": "052-2009, band 9.6.3"},
      {"savol": "Har xil chizmalar bo'yicha tayyorlangan skolzun qalpoqlarini bitta aravachaga o'rnatish mumkinmi?", "variantlar": ["Ha", "Yo'q, ruxsat etilmaydi", "Faqat depo ta'mirida", "Faqat kapital ta'mirda"], "togri": 1, "izoh": "052-2009, band 9.6.3"},
    ],
  },
  {
    nom: "Ta'mirlash texnologiyasi — qaror qabul qilish",
    daraja: "Yuqori",
    tavsif: "Defektatsiya kartalari: qaysi nuqsonda brak, qaysida payvand yoki naplavka.",
    savollar: [
      {"savol": "Buksa proyomida kanavkasimon yeyilish 2,5 mm chiqdi. Qaror?", "variantlar": ["Bunday ramani ta'mirlash taqiqlanadi — brak", "Qoldiriladi", "Naplavka qilinadi", "Stanokda ishlov beriladi"], "togri": 0, "izoh": "052-2009, band 8.3"},
      {"savol": "Tayanch yuzada kanavka kengligi 15 mm, chuqurligi 1,5 mm. Qaror?", "variantlar": ["Brak", "Qoldiriladi", "Stanokda mexanik ishlov berish", "Naplavka"], "togri": 2, "izoh": "Ilova Ж, yon rama kartasi: kenglik ≤20 mm va chuqurlik ≤2 mm"},
      {"savol": "Tayanch yuzani mexanik ishlagandan keyin priliv balandligi kamida qancha qolishi kerak?", "variantlar": ["0,5 mm dan kam bo'lmasin", "2 mm", "1 mm", "3 mm"], "togri": 0, "izoh": "052-2009, band 8.10 — freza rama tanasiga kirib ketmasligi uchun"},
      {"savol": "Buksa yo'naltiruvchilarining yeyilishi proyom kengligi bo'yicha 6 mm. Qaror?", "variantlar": ["Stanokda ishlov", "Naplavka bilan ta'mirlash", "Qoldiriladi", "Brak"], "togri": 1, "izoh": "Ilova Ж: ≤8 mm bo'lsa naplavka, >8 mm bo'lsa brak"},
      {"savol": "Depo ta'mirida buksalar uchun yo'naltiruvchi tekisliklarning yeyilishi qancha bo'lishi mumkin?", "variantlar": ["2 mm", "Cheklov yo'q", "8 mm", "4 mm dan ko'p emas"], "togri": 3, "izoh": "052-2009, band 8.7 — buksa proyomi kengligi bo'yicha"},
      {"savol": "Yeyilgan vertikal yo'naltiruvchi tekisliklar qanday tiklanadi?", "variantlar": ["Yeyilishga chidamli naplavka, qattiqligi 240…300 HB, so'ngra stanokda ishlov", "Tiklanmaydi", "Payvand bilan", "Plastina qo'yiladi"], "togri": 0, "izoh": "052-2009, band 8.8"},
      {"savol": "Triangel osmasi kronshteynida 25 mm uzunlikdagi yoriq. Qaror?", "variantlar": ["Brak", "Naplavka", "Qoldiriladi", "Payvand bilan ta'mirlash"], "togri": 3, "izoh": "Ilova Ж: <32 mm bo'lsa payvand, ≥32 mm bo'lsa brak"},
      {"savol": "Bashmak osmasi valigi prilivi devorida KO'NDALANG yoriq. Qaror?", "variantlar": ["Naplavka", "Payvand bilan ta'mirlash", "Brak", "Qoldiriladi"], "togri": 2, "izoh": "Ilova Ж: bo'ylama — payvand, ko'ndalang — brak"},
      {"savol": "Friksion plankalarni biriktirish joyida diagonal bo'yicha 2 ta «quloqcha» uchgan. Qaror?", "variantlar": ["Brak", "Qoldiriladi", "Butun rama almashtiriladi", "Payvand bilan ta'mirlash"], "togri": 3, "izoh": "052-2009, band 8.4.5: ≤2 ta payvand, >2 ta brak"},
      {"savol": "Yon ramaning pastki poyasida yoriq topildi. Qaror?", "variantlar": ["МПК takrorlanadi", "Naplavka", "Uzunligiga qarab payvand", "Brak — ta'mirga tegishli emas"], "togri": 3, "izoh": "Ilova Ж, yon rama kartasi, poz. 9 va 18"},
      {"savol": "Nadressor balkasi yuqori poyasida 200 mm uzunlikdagi BO'YLAMA yoriq. Qaror?", "variantlar": ["Brak", "Naplavka", "Plastina qo'yiladi", "Payvand bilan ta'mirlash"], "togri": 3, "izoh": "Ilova Ж: bo'ylama ≤250 mm — payvand, >250 mm — brak"},
      {"savol": "Nadressor balkasi yuqori poyasida KO'NDALANG yoriq. Qaror?", "variantlar": ["Naplavka", "Payvand", "Brak", "Uzunligiga bog'liq"], "togri": 2, "izoh": "Ilova Ж, nadressor balkasi kartasi, poz. 3"},
      {"savol": "Yoriq balkaning bo'ylama o'qiga 40° burchak ostida joylashgan. U qanday hisoblanadi?", "variantlar": ["Diagonal", "Hisobga olinmaydi", "Ko'ndalang", "Bo'ylama"], "togri": 2, "izoh": "052-2009, 9.1-rasm izohi: 30° dan katta burchak — ko'ndalang"},
      {"savol": "Podpyatnik tayanch yuzasining qolgan qalinligi 16 mm chiqdi. Qaror?", "variantlar": ["Qoldiriladi", "Naplavka", "Payvand", "Brak"], "togri": 3, "izoh": "Ilova Ж: ≥18 mm naplavka, <18 mm brak"},
      {"savol": "Nadressor balkasi qiya tekisligining qolgan qalinligi 6 mm. Qaror?", "variantlar": ["Brak", "Naplavka", "Plastina-vstavkani payvandlab ta'mirlash", "Qoldiriladi"], "togri": 2, "izoh": "Ilova Ж: ≥7 mm naplavka, <7 mm plastina-vstavka (052-2009, 9.5.3)"},
      {"savol": "Cheklovchi burtning qolgan qalinligi 8 mm. Qaror?", "variantlar": ["Naplavka", "Qoldiriladi", "Brak", "Payvand"], "togri": 2, "izoh": "Ilova Ж: ≥10 mm naplavka, <10 mm brak"},
      {"savol": "Podpyatnikning ichki kolonkasida yoriq. Qaror?", "variantlar": ["Uzunligidan qat'i nazar ta'mirga tegishli emas — brak", "Naplavka", "Vtulka qo'yiladi", "Uzunligiga qarab payvand"], "togri": 0, "izoh": "052-2009, band 9.2"},
      {"savol": "Podpyatnikdagi yoriqlarning umumiy uzunligi qancha bo'lsa payvandlanadi?", "variantlar": ["500 mm gacha", "100 mm gacha", "150 mm gacha", "250 mm dan oshmasa"], "togri": 3, "izoh": "052-2009, band 9.4 — halqasimon uzuq-yuluq, markazdan ≥80 mm"},
      {"savol": "Podpyatnikni stanokda ishlaganda qanday galtel ta'minlanishi shart?", "variantlar": ["Galtel kerak emas", "5…6 mm radiusli", "3…4 mm radiusli", "1…2 mm radiusli"], "togri": 2, "izoh": "052-2009, band 9.4.6 — galtelning yo'qligi ruxsat etilmaydi"},
      {"savol": "Skolzun qalpog'i uchun prilivning balandligi (balka pastki tekisligidan) qancha bo'lishi kerak?", "variantlar": ["330 (−6) mm", "315 (−6) mm", "300 (−6) mm", "320 (−6) mm"], "togri": 1, "izoh": "052-2009, band 9.6.2"},
    ],
  },
  {
    nom: "Yig'uv va chiqarishdagi nazorat",
    daraja: "Yuqori",
    tavsif: "Yig'uv tartibi, obod qalinligi, zazorlar, ponalar holati va yakuniy nazorat.",
    savollar: [
      {"savol": "Aravacha qanday ketma-ketlikda yig'iladi?", "variantlar": ["Ixtiyoriy", "Ajratishga teskari ketma-ketlikda", "Avval tormoz, keyin rama", "Chizmaga qarab"], "togri": 1, "izoh": "052-2009, band 14.1"},
      {"savol": "Harakatlanuvchi friksion plankalar qaysi prujinalarga o'rnatiladi?", "variantlar": ["Farqi yo'q", "O'rtachalariga", "Eng past prujinalarga", "Eng baland prujinalarga"], "togri": 3, "izoh": "052-2009, band 14.2"},
      {"savol": "Tayanch balka o'rnatilgandan keyin qanday bo'lishi kerak?", "variantlar": ["Yon ramalar pazlarida erkin siljishi kerak", "Payvandlangan", "Boltlangan", "Qattiq qotirilgan"], "togri": 0, "izoh": "052-2009, band 14.2"},
      {"savol": "110 ming km normativda depo ta'mirida g'ildirak obodining qalinligi kamida qancha?", "variantlar": ["27 mm", "24 mm", "35 mm", "30 mm"], "togri": 0, "izoh": "052-2009, 14.1-jadval; kapital ta'mirda 30 mm"},
      {"savol": "210 ming km normativda kapital ta'mirda obod qalinligi kamida qancha?", "variantlar": ["35 mm", "40 mm", "45 mm", "55 mm"], "togri": 3, "izoh": "052-2009, 14.1-jadval"},
      {"savol": "Bitta ikki o'qli aravachada g'ildiraklar diametrlari farqi qancha bo'lsa podkatka taqiqlanadi?", "variantlar": ["Cheklov yo'q", "10 mm dan ortiq", "40 mm dan ortiq", "20 mm dan ortiq"], "togri": 3, "izoh": "052-2009, band 14.7"},
      {"savol": "Diametrlari farq qiladigan g'ildirak juftlari qanday joylashtiriladi?", "variantlar": ["Farqi yo'q", "Diagonal bo'yicha", "Kichikroq diametrlilar aravachaning ichkarisiga", "Kichikroq diametrlilar tashqariga"], "togri": 2, "izoh": "052-2009, band 14.7"},
      {"savol": "Depo ta'mirida buksa bilan umumiy zazor aravacha o'qi bo'ylab qancha (umumiy holda)?", "variantlar": ["3…12 mm", "5…12 mm", "5…11 mm", "5…14 mm"], "togri": 3, "izoh": "050-2020, band 5.2.13; 052-2009, 14.8. 18-100 uchun 3…12 mm"},
      {"savol": "Kapital ta'mirda buksa zazori aravacha o'qiga ko'ndalang qancha (umumiy holda)?", "variantlar": ["5…10 mm", "5…12 mm", "5…13 mm", "5…11 mm"], "togri": 3, "izoh": "052-2009, band 14.8"},
      {"savol": "Umumiy zazorni hisoblashda qaysi qiymatlar olinadi?", "variantlar": ["O'rtacha", "Eng kichik", "Ixtiyoriy", "Eng katta"], "togri": 1, "izoh": "050-2020, band 5.2.13"},
      {"savol": "Bitta aravachada tavr va quticha kesimli yon ramalarni aralash o'rnatish mumkinmi?", "variantlar": ["Faqat depo ta'mirida", "Yo'q, taqiqlanadi", "Faqat 18-100 uchun", "Ha"], "togri": 1, "izoh": "052-2009, band 14.10"},
      {"savol": "Depo ta'mirida friksion ponaning ko'tarilishiga ruxsat beriladimi?", "variantlar": ["Faqat kapital ta'mirda", "Ha, 12 mm gacha", "Yo'q, hatto bitta pona uchun ham", "Ha, 5 mm gacha"], "togri": 2, "izoh": "050-2020, band 5.5; 052-2009, band 18.4"},
      {"savol": "Depo ta'mirida ponaning pasayishi qancha bo'lishi mumkin?", "variantlar": ["4 mm", "8 mm", "12 mm dan ko'p emas", "16 mm"], "togri": 2, "izoh": "052-2009, band 18.4"},
      {"savol": "Kapital ta'mirda ponalar qanday holatda bo'lishi kerak?", "variantlar": ["4…12 mm ga pasaytirilgan", "Ko'tarilgan", "0…4 mm ga pasaytirilgan", "Bir tekisda"], "togri": 0, "izoh": "052-2009, band 18.4"},
      {"savol": "Aravachaning yosh guruhi raqami nimaga qarab belgilanadi?", "variantlar": ["Eng erta tayyorlangan element bo'yicha", "Eng kech tayyorlangan element bo'yicha", "Ramaning yoshi bo'yicha", "O'rtacha yosh bo'yicha"], "togri": 0, "izoh": "052-2009, band 18.3"},
      {"savol": "1997-yildan boshlab qurilgan aravachalar qaysi yosh guruhiga kiradi?", "variantlar": ["Nolinchi", "Birinchi", "Ikkinchi", "Uchinchi"], "togri": 0, "izoh": "052-2009, band 18.3 — «Normы» 1996-yil nashri"},
      {"savol": "Qo'zg'almas friksion plankaning yon rama yuzasiga zich yotishida mahalliy zazor qancha bo'lishi mumkin?", "variantlar": ["1 mm dan ko'p emas", "0,5 mm", "3 mm", "2 mm"], "togri": 0, "izoh": "052-2009, band 18.5"},
      {"savol": "To'rt o'qli vagonlarda skolzunlardagi umumiy zazor qancha bo'lishi kerak (umumiy holda)?", "variantlar": ["6…12 mm", "4…10 mm", "0…6 mm", "6 mm dan kam emas va 16 mm dan ko'p emas"], "togri": 3, "izoh": "052-2009, band 18.8"},
      {"savol": "Sisternalarda skolzunlardagi umumiy zazor qancha?", "variantlar": ["6…12 mm", "6…16 mm", "4…10 mm", "5…10 mm"], "togri": 2, "izoh": "052-2009, band 18.8"},
      {"savol": "Zazorlarni rostlash qanday yo'l uchastkasida bajariladi?", "variantlar": ["Egri yo'lda", "To'g'ri, uzunligi 30 m dan kam bo'lmagan, yo'l kengligi 1520 ± 2 mm", "Faqat depo ichida", "Har qanday yo'lda"], "togri": 1, "izoh": "052-2009, band 18.17"},
    ],
  },
  {
    nom: "«Pona – planka» uzeli va klepka ishlari",
    daraja: "Yuqori",
    tavsif: "Pona turlari va chizmalari, almashtirish qoidalari, plankalarni klepka qilish va zaklepkalar.",
    savollar: [
      {"savol": "«Pona – friksion planka» uzeli nechta elementdan iborat?", "variantlar": ["To'rtta", "Uchta", "Beshta", "Ikkita"], "togri": 1, "izoh": "052-2009, band 10.1 — tarkibiy planka, pona va balkaning qiya yuzasi"},
      {"savol": "Depo ta'mirida 18-100 modeliga qaysi chizma bo'yicha pona o'rnatiladi?", "variantlar": ["1699.04.007", "ВАГР-0113.50.00.002", "М 1698.00.003 yoki М 1698.00.003-01 (СЧ 35)", "100.30.001-1"], "togri": 2, "izoh": "052-2009, band 10.1.2"},
      {"savol": "Po'lat friksion ponani ta'mirlash mumkinmi?", "variantlar": ["Yo'q, taqiqlanadi", "Faqat depo ta'mirida", "Ha, naplavka bilan", "Ha, payvand bilan"], "togri": 0, "izoh": "052-2009, band 10.1.2"},
      {"savol": "Bitta vagon ostidagi aravachalarga po'lat va cho'yan ponalarni birga o'rnatish mumkinmi?", "variantlar": ["Ha", "Faqat kapital ta'mirda", "Faqat depo ta'mirida", "Yo'q, taqiqlanadi"], "togri": 3, "izoh": "052-2009, band 10.1.2"},
      {"savol": "С 03.04 loyihasi bo'yicha friksion pona qanday o'rnatiladi?", "variantlar": ["Faqat С 03.04 loyihasidagi friksion planka bilan juft holda", "Plankasiz", "Har qanday planka bilan", "М 1698 plankasi bilan"], "togri": 0, "izoh": "052-2009, band 10.1.2"},
      {"savol": "Kapital ta'mirda friksion ponalar bilan nima qilinadi?", "variantlar": ["Yangi cho'yan ponalarga almashtiriladi", "Qoldiriladi", "O'lchanadi", "Naplavka qilinadi"], "togri": 0, "izoh": "052-2009, band 10.2"},
      {"savol": "ВАГР-0113.50.00.002 chizmasi bo'yicha ponalar qanday normativda o'rnatiladi?", "variantlar": ["160 ming km dan ko'p bo'lmagan", "110 ming km", "Cheklov yo'q", "210 ming km"], "togri": 0, "izoh": "052-2009, 10.1.2-band izohi"},
      {"savol": "Friksion ponani o'rnatish va almashtirish qanday bajariladi?", "variantlar": ["Komplekt bilan", "Bittalab", "Faqat bir tomondan", "Ixtiyoriy"], "togri": 0, "izoh": "052-2009, 10.1.2-band izohi"},
      {"savol": "Depo ta'mirida ponani almashtirmasdan qoldirish uchun umumiy yeyilish qancha bo'lishi kerak?", "variantlar": ["3 mm gacha, bir tomondan 2 mm dan ko'p emas", "2 mm gacha", "5 mm gacha", "Cheklov yo'q"], "togri": 0, "izoh": "052-2009, band 10.3"},
      {"savol": "Kapital ta'mirda 18-100 modeliga qanday friksion plankalar o'rnatiladi?", "variantlar": ["М 1698 ПКБ ЦВ loyihasi bo'yicha yangi tarkibiy plankalar", "Eskilari qoldiriladi", "16 mm li yaxlit plankalar", "С 03.04 plankalari"], "togri": 0, "izoh": "052-2009, band 10.4"},
      {"savol": "Qo'zg'almas friksion plankalar vertikal tekislikda qanday joylashishi kerak?", "variantlar": ["Qat'iy parallel", "Parallel bo'lmasligi — pastga 4…10 mm ga kengayishi kerak", "Farqi yo'q", "Pastga toraytirilgan"], "togri": 1, "izoh": "052-2009, band 10.6"},
      {"savol": "«Г» va «Д» o'lchamlari farqi («Ж» va «З» nuqtalarida) qancha bo'lishi mumkin?", "variantlar": ["2 mm", "1 mm", "3 mm dan ko'p emas", "5 mm"], "togri": 2, "izoh": "052-2009, band 10.6"},
      {"savol": "«Е» o'lchami qanday aniqlanadi?", "variantlar": ["O'lchanmaydi", "«Г» va «Д» yig'indisi bilan", "«Г» va «Д» ning yarim farqi bilan", "«Г» ni 2 ga bo'lib"], "togri": 2, "izoh": "052-2009, band 10.6"},
      {"savol": "Klepka ishlaridan oldin ishlangan yuza qanday g'adir-budurlikka mos bo'lishi kerak?", "variantlar": ["Ra 12,5", "Talab yo'q", "Ra 6,3", "Ra 25"], "togri": 0, "izoh": "052-2009, band 10.7"},
      {"savol": "Yon ramada zaklepkalar uchun teshik diametri qancha bo'lishi kerak?", "variantlar": ["Ø 20 (+0,84) mm", "Ø 23 (+0,84) mm", "Ø 21 (+0,84) mm", "Ø 18 (+0,84) mm"], "togri": 2, "izoh": "052-2009, band 10.8"},
      {"savol": "Plankalar qanday zaklepkalar bilan biriktiriladi?", "variantlar": ["Payvand bilan", "Yarim dumaloq kallakli, Ø 21 mm", "Botiq (potaynoy) kallakli, Ø 20 mm ГОСТ 10300", "Boltlar bilan"], "togri": 2, "izoh": "052-2009, band 10.8"},
      {"savol": "Issiq klepka kuchi qancha bo'lishi kerak?", "variantlar": ["10 tk dan kam emas", "40 tk", "15 tk dan kam emas", "25 tk dan kam emas"], "togri": 3, "izoh": "052-2009, band 10.8"},
      {"savol": "Zaklepkani qizdirish harorati qanday oraliqda bo'lishi kerak?", "variantlar": ["1200…1300 °C", "800…900 °C", "600…700 °C", "1050…1100 °C"], "togri": 3, "izoh": "052-2009, band 10.8"},
      {"savol": "Bo'shashgan zaklepkalar bilan nima qilinadi?", "variantlar": ["Payvandlanadi", "Yangisiga almashtiriladi, planka qayta klepkalanadi", "Tortiladi", "Chekanka qilinadi"], "togri": 1, "izoh": "052-2009, band 10.9 — payvandlash, tortish va chekanka taqiqlanadi"},
      {"savol": "Elektropayvand bilan payvandlangan friksion plankali yon ramani ta'mirdan chiqarish mumkinmi?", "variantlar": ["Faqat depo ta'mirida", "Faqat 18-100 uchun", "Taqiqlanadi", "Ha"], "togri": 2, "izoh": "052-2009, band 10.9"},
    ],
  },
  {
    nom: "Buzmasdan nazorat (НК)",
    daraja: "Yuqori",
    tavsif: "МПК va ВТК usullari, zonalar, parametrlar, o'tkazish tartibi va baholash.",
    savollar: [
      {"savol": "Tip 2 aravachaning yon ramasi va nadressor balkasi qaysi usulda tekshiriladi?", "variantlar": ["Ultratovush", "Faqat МПК", "МПК yoki ВТК", "Faqat ВТК"], "togri": 1, "izoh": "ПР НК В.3, 4.1-jadval — quyma detallar uchun faqat МПК"},
      {"savol": "НК da arbitraj (yakuniy) usul qaysi?", "variantlar": ["Ultratovush", "Vizual ko'rik", "ВТК", "МПК"], "togri": 3, "izoh": "ПР НК В.3, band 5.1.1"},
      {"savol": "МПК nima degani?", "variantlar": ["Mexanik nazorat", "Modul nazorati", "Magnitoxukukli nazorat", "Metall nazorati"], "togri": 2, "izoh": "Магнитопорошковый контроль"},
      {"savol": "ВТК nima degani?", "variantlar": ["Uyurma tokli nazorat (вихретоковый)", "Vertikal nazorat", "Vizual nazorat", "Vaqtinchalik nazorat"], "togri": 0, "izoh": "Вихретоковый контроль"},
      {"savol": "МПК da detal yuzasidagi Ht qanday bo'lishi kerak?", "variantlar": ["30 А/см dan kam emas", "20 А/см dan kam emas", "50 А/см dan kam emas", "10 А/см dan kam emas"], "togri": 1, "izoh": "ПР НК В.3, 5.2 va 5.3-jadvallar"},
      {"savol": "СПП nima degani?", "variantlar": ["Statik magnitlash", "Qo'yilgan maydon usuli — suspenziya magnitlash bilan bir vaqtda suriladi", "Sinov usuli", "Sirkulyar magnitlash"], "togri": 1, "izoh": "Способ приложенного поля"},
      {"savol": "ВТК da aniqlanishi kerak bo'lgan sun'iy nuqsonning chuqurligi qancha (umumiy holda)?", "variantlar": ["150 ± 50 mkm", "5000 mkm", "3000 ± 100 mkm", "500 ± 100 mkm"], "togri": 2, "izoh": "ПР НК В.3, 5.1-jadval; kengligi 500 mkm dan ko'p emas"},
      {"savol": "Nadressor balkasining pastki poyasidagi majburiy nazorat zonasi qanday chegaralarda?", "variantlar": ["Markazdan 100 mm", "Butun poyas bo'yicha", "Markazdan 250 mm, balandligi 50 mm", "Markazdan 520 mm, balandligi 50 mm"], "togri": 3, "izoh": "052-2009, 7.2-jadval"},
      {"savol": "Yon ramada nechta nazorat zonasi belgilangan?", "variantlar": ["4 ta", "7 ta", "6 ta", "5 ta"], "togri": 1, "izoh": "052-2009, 7.2-jadval: 1–7 zonalar"},
      {"savol": "Detalni НК ga tayyorlashda nima qilinadi?", "variantlar": ["Metallgacha tozalanadi — zang, moy, bo'yoq olib tashlanadi", "Bo'yaladi", "Qizdiriladi", "Faqat changi artiladi"], "togri": 0, "izoh": "ПР НК В.3, band 6.1.2"},
      {"savol": "Vizual ko'rikda ruxsat etilmagan nuqson topilgan detal bilan nima qilinadi?", "variantlar": ["НК ga qo'yilmaydi", "O'lchanadi", "Qayta tozalanadi", "НК ga qo'yiladi"], "togri": 0, "izoh": "ПР НК В.3, band 6.1.3"},
      {"savol": "НК vositalarini tayyorlash qachon bajariladi?", "variantlar": ["Yiliga bir marta", "Oyiga bir marta", "Har ish smenasi boshida va o'zgartkich almashtirilganda", "Talab yo'q"], "togri": 2, "izoh": "ПР НК В.3, band 6.2.1"},
      {"savol": "Solenoidni diskret siljitganda qo'shni uchastkalar bir-birini qanchaga qoplashi kerak?", "variantlar": ["Qoplash shart emas", "Kamida 10 mm", "Kamida 50 mm", "Kamida 20 mm"], "togri": 3, "izoh": "ПР НК В.3, band 7.2.2.3"},
      {"savol": "«30° qoidasi» nimani anglatadi?", "variantlar": ["Detal 30° ga buriladi", "Kuch chiziqlari bilan nuqson orasidagi burchak 30° dan kichik bo'lsa, nuqson aniqlanmasligi mumkin", "Harorat 30 °C bo'lishi kerak", "Magnit 30° ostida qo'yiladi"], "togri": 1, "izoh": "ПР НК В.3, band 7.2.4"},
      {"savol": "Qo'l elektromagniti detal yuzasiga nechta yo'nalishda qo'yiladi?", "variantlar": ["To'rtta", "Uchta", "Ikkita o'zaro perpendikulyar", "Bitta"], "togri": 2, "izoh": "ПР НК В.3, band 7.2.4"},
      {"savol": "Magnit suspenziyasi qanday suriladi?", "variantlar": ["Cho'tka bilan surtish", "Kuchli oqim bilan", "Latta bilan", "Kuchsiz oqim bilan quyish yoki purkash"], "togri": 3, "izoh": "ПР НК В.3, band 7.2.6.1 — oqim zarrachalarni yuvib yubormasligi kerak"},
      {"savol": "Indikator rasmi soxta ekanini qanday aniqlanadi?", "variantlar": ["Fotosurat olinadi", "O'lchab ko'riladi", "Aniqlab bo'lmaydi", "Detal artilib nazorat takrorlanadi — valik yo'qolsa yoki o'zgarsa, soxta"], "togri": 3, "izoh": "ПР НК В.3, band 7.2.7.4"},
      {"savol": "Chiziqli indikator rasmi qanday ta'riflanadi?", "variantlar": ["Uzunligi kengligiga teng", "Uzunligi 5 mm dan katta", "Uzunligi kengligining uch barobaridan katta", "Doira shaklida"], "togri": 2, "izoh": "ПР НК В.3, band 3.3.14"},
      {"savol": "МПК bo'yicha detal qachon talablarga muvofiq emas deb topiladi?", "variantlar": ["Majburiy НК zonalarida chiziqli indikator rasmi topilsa", "Faqat yoriq ko'rinsa", "Har qanday to'planish bo'lsa", "Kompakt indikator rasmi bo'lsa"], "togri": 0, "izoh": "ПР НК В.3, band 8.5"},
      {"savol": "ВТК da nechta indikator izi brak berish uchun yetarli?", "variantlar": ["Ikkita", "Bitta", "Uchta", "Beshta"], "togri": 1, "izoh": "ПР НК В.3, band 8.3"},
      {"savol": "Detalning qoldiq magnitlanishi qancha bo'lishi kerak?", "variantlar": ["20 А/см dan ko'p emas", "2 А/см dan ko'p emas", "10 А/см dan ko'p emas", "5 А/см dan ko'p emas"], "togri": 3, "izoh": "ПР НК В.3, band 7.2.10.2"},
      {"savol": "НК natijalari jurnallari qancha muddat saqlanadi?", "variantlar": ["Kamida 5 yil", "3 yil", "1 yil", "10 yil"], "togri": 0, "izoh": "ПР НК В.3, band 8.10"},
      {"savol": "НК ish joyida umumiy va mahalliy yoritilganlik qancha bo'lishi kerak?", "variantlar": ["1000 lk dan kam emas", "200 lk dan kam emas", "1500 lk", "500 lk dan kam emas"], "togri": 3, "izoh": "ПР НК В.3, band 4.3.3; МПК da ko'rikda 1000 lk"},
      {"savol": "UB nurlanish ishlatilganda ko'rinadigan yorug'lik qancha bo'lishi kerak?", "variantlar": ["100 lk", "300 lk", "20 lk dan ko'p emas", "500 lk"], "togri": 2, "izoh": "ПР НК В.3, band 4.3.4.2; UB quvvati 20 Вт/м² dan kam emas"},
      {"savol": "НК ish joyida havo va obyekt harorati qanday oraliqda bo'lishi kerak?", "variantlar": ["0 dan +30 °C", "+10 dan +50 °C", "Cheklov yo'q", "+5 dan +40 °C"], "togri": 3, "izoh": "ПР НК В.3, band 4.3.7"},
    ],
  },
  {
    nom: "Payvand, naplavka va materiallar",
    daraja: "Usta",
    tavsif: "Payvand va naplavka materiallari, rejimlar, prujinalarni brak qilish va ish joyi talablari.",
    savollar: [
      {"savol": "Prujinalar aravachadan qanday holatda yechiladi?", "variantlar": ["Faqat nosozlari", "Faqat kapital ta'mirda", "Texnik holatidan qat'i nazar hammasi", "Yechilmaydi"], "togri": 2, "izoh": "052-2009, band 11.1"},
      {"savol": "Prujinani brak qilish uchun korroziya qancha bo'lishi kerak?", "variantlar": ["O'ram kesimi maydonining 5% dan ortiq", "Har qanday korroziya", "O'ram kesimi maydonining 20% dan ortiq", "O'ram kesimi maydonining 10% dan ortiq"], "togri": 3, "izoh": "052-2009, band 11.1"},
      {"savol": "Yangi tayyorlangan prujinalar qaysi standartga mos bo'lishi shart?", "variantlar": ["ГОСТ 9246", "ГОСТ 32400", "ГОСТ 1452", "ГОСТ 14959"], "togri": 2, "izoh": "052-2009, band 11.1"},
      {"savol": "Payvand va naplavka ishlari qaysi yo'riqnomalar bo'yicha bajariladi?", "variantlar": ["РД 32 ЦВ 050-2020", "Faqat ЦВ-201-2015", "ЦВ-201-2015 va ВНИИЖТ ning ТИ-05-01-06/НБ, ТИ-БР-2010", "ГОСТ 9467"], "togri": 2, "izoh": "052-2009, band 13.1"},
      {"savol": "Payvand ishlari qayerda bajariladi?", "variantlar": ["Har qanday joyda", "Yig'uv uchastkasida", "Kantovatel va payvand uskunalari bilan jihozlangan maxsus payvand pozitsiyalarida", "Ochiq havoda"], "togri": 2, "izoh": "052-2009, band 13.1"},
      {"savol": "Naplavka nima uchun bajariladi?", "variantlar": ["Og'irlikni oshirish uchun", "Yuzaga metall qo'shib, keyin mexanik ishlov bilan chizma o'lchamiga keltirish uchun", "Detalni bo'yash uchun", "Yoriqni yashirish uchun"], "togri": 1, "izoh": "052-2009, band 13.2"},
      {"savol": "Flyus ostida avtomatik naplavkada qaysi flyus ishlatiladi?", "variantlar": ["ЭЖТ-1", "УОНИ-13/55", "АН-348-А ГОСТ 9087", "Св-08Г2С ГОСТ 2246"], "togri": 2, "izoh": "052-2009, band 13.3.1"},
      {"savol": "Flyus ostida avtomatik naplavkada qaysi payvand simi ishlatiladi?", "variantlar": ["Св-08Г2С", "Св-10ХГ2СМФ yoki kukunli sim ПП-АН180МН", "ЭЖТ-1", "УОНИ-13/55"], "togri": 1, "izoh": "052-2009, band 13.3.1"},
      {"savol": "Qoplamali elektrodlar bilan qo'lda yeyilishga chidamli naplavkada qaysi elektrod ishlatiladi?", "variantlar": ["УОНИ-13/55", "ЭЖТ-1 ТУ 1272-252-01124323-2008", "Св-08Г2С", "Э-50 А"], "togri": 1, "izoh": "052-2009, band 13.3.3"},
      {"savol": "Himoya gazida naplavkada qaysi gaz ishlatiladi?", "variantlar": ["1-nav uglerod ikki oksidi ГОСТ 8050", "Argon", "Geliy", "Azot"], "togri": 0, "izoh": "052-2009, band 13.3.2"},
      {"savol": "Boshqa markadagi naplavka materialini qo'llash uchun qanday shart bor?", "variantlar": ["Umuman mumkin emas", "Cheklov yo'q", "Naplavkada 240…300 HB qattiqlikni ta'minlasa va NTD da ko'zda tutilgan bo'lsa", "Faqat ВНИИЖТ ruxsati bilan"], "togri": 2, "izoh": "052-2009, band 13.3.4"},
      {"savol": "Yeyilishga chidamlilik talab qilinmaydigan qo'lda payvandlashda qaysi elektrod ishlatiladi?", "variantlar": ["Св-10ХГ2СМФ", "Э-50 А ГОСТ 9467 (УОНИ-13/55 va boshqalar)", "ПП-АН180МН", "ЭЖТ-1"], "togri": 1, "izoh": "052-2009, band 13.4.1"},
      {"savol": "Mexanizatsiyalangan payvandlashda (yeyilishga chidamlilik talab qilinmaganda) qaysi sim ishlatiladi?", "variantlar": ["Св-10ХГ2СМФ", "ПП-АН180МН", "ЭЖТ-1", "Св-08Г2С ГОСТ 2246"], "togri": 3, "izoh": "052-2009, band 13.4.2"},
      {"savol": "Naplavka qilingan yuzalar qayerda mexanik ishlanadi?", "variantlar": ["Shlifovka mashinasi bilan", "Ixtisoslashtirilgan frezerlash, teshish va rendalash stanoklarida", "Ishlanmaydi", "Qo'lda bolg'a bilan"], "togri": 1, "izoh": "052-2009, band 13.5"},
      {"savol": "Payvand ish joyi qanday ventilyatsiya bilan jihozlangan bo'lishi kerak?", "variantlar": ["Ventilyator", "Mahalliy so'rish ventilyatsiyasi", "Umumiy almashtirish ventilyatsiyasi", "Talab yo'q"], "togri": 1, "izoh": "052-2009, band 13.7"},
      {"savol": "To'rt o'qli aravachaning biriktiruvchi balkasida payvand ishlari qaysi hujjat bo'yicha bajariladi?", "variantlar": ["ТК-232 I, II, III qismlari", "ЦВ-201-2015", "ТИ-БР-2010", "ТК-230 ПКБ ЦВ"], "togri": 0, "izoh": "052-2009, band 13.6"},
      {"savol": "Texnologik jihozlarning tavsiya etiladigan ro'yxati qaysi ilovada berilgan?", "variantlar": ["Ж ilovasida", "Б ilovasida", "В ilovasida", "А ilovasida"], "togri": 3, "izoh": "052-2009, band 13.7"},
      {"savol": "Naplavka qattiqligi nima uchun ikki tomondan chegaralangan?", "variantlar": ["Chegara yo'q", "O'lchash qulayligi uchun", "Yumshoq naplavka tez yeyiladi, qattiq naplavka mo'rt bo'lib yorilib ketadi", "Faqat an'ana"], "togri": 2, "izoh": "240…300 HB oralig'i (052-2009, 6.5 va 13.3.4-bandlar)"},
      {"savol": "Naplavka qattiqligi qaysi standartlar bo'yicha o'lchanadi?", "variantlar": ["ГОСТ 1452 va ГОСТ 9246", "ГОСТ 9012-59 va ГОСТ 9013-59", "ГОСТ 8050", "ГОСТ 9087"], "togri": 1, "izoh": "052-2009, band 6.5 — ТЭМП 3 tipidagi qattiqlik o'lchagich"},
      {"savol": "Yeyilishga chidamli naplavka bilan oddiy payvand orasidagi farq nimada?", "variantlar": ["Naplavka faqat kapital ta'mirda", "Oddiy payvand taqiqlanadi", "Naplavka ishqalanuvchi yuzalar uchun, oddiy payvand yoriqlarni bitirish uchun; material va rejim boshqacha", "Farq yo'q"], "togri": 2, "izoh": "052-2009, bandlar 13.3 va 13.4"},
    ],
  },
  {
    nom: "Usta darajasi — aralash masalalar",
    daraja: "Usta",
    tavsif: "Bir necha hujjatni bog'lash, model bo'yicha farqlar va amaliy vaziyatlar.",
    savollar: [
      {"savol": "18-100 aravachasi, depo ta'miri. Dvijok «0» dan o'ngda 6 bo'linma ko'rsatdi. «З» va xulosa?", "variantlar": ["З = 170 mm, brak", "З = 184 mm, yaroqli", "З = 167 mm, brak", "З = 167 mm, yaroqli"], "togri": 3, "izoh": "K = −6 → З = 167 mm. ДР uchun ≥166 mm talab qilinadi → yaroqli"},
      {"savol": "18-100 aravachasi, kapital ta'mir. «K» = −3. Xulosa?", "variantlar": ["З = 171 mm, yaroqli", "З = 179 mm, yaroqli", "З = 166 mm, yaroqli", "З = 171 mm, me'yordan chiqqan"], "togri": 3, "izoh": "КР uchun 174 < З < 179 mm talab qilinadi; 171 mm — me'yordan chiqqan"},
      {"savol": "C₂past = −5 mm, C₂yuqori = −1 mm. K₂ va xulosa?", "variantlar": ["K₂ = 2 mm, yaroqli", "K₂ = 4 mm, me'yordan chiqqan", "K₂ = 6 mm, yaroqli", "K₂ = 4 mm, yaroqli"], "togri": 1, "izoh": "K₂ = |(−5)−(−1)| = 4 mm > 3 mm → shart bajarilmadi"},
      {"savol": "18-9801 aravachasi, kapital ta'mir. Buksa proyomi kengligi qancha bo'lishi kerak?", "variantlar": ["335 ± 1 mm", "338 mm dan ko'p emas", "342 mm dan ko'p emas", "335 (+3/−1) mm"], "togri": 3, "izoh": "050-2020, band 5.2.1 — 18-9801 uchun alohida dopusk"},
      {"savol": "18-100 aravachasi, depo ta'miri. Buksa proyomi kengligi 340 mm. Xulosa?", "variantlar": ["Aniqlab bo'lmaydi", "Yaroqli, chunki 342 dan kichik", "Me'yordan chiqqan — 18-100 uchun 338 mm dan ko'p emas", "Yaroqli, umumiy me'yor 342 mm"], "togri": 2, "izoh": "050-2020, band 5.2.1 — model uchun alohida me'yor"},
      {"savol": "18-9801 aravachasi. Yo'naltiruvchilar kengligi «В» qancha bo'lishi kerak?", "variantlar": ["154 mm dan kam emas", "155 mm dan kam emas", "160 ± 1 mm", "160 (+1/−2) mm"], "togri": 3, "izoh": "050-2020, band 5.2.3"},
      {"savol": "18-9801, depo ta'miridan chiqarish. «В» ning eng kichik qiymati?", "variantlar": ["160 mm", "154 mm", "150 mm", "155 mm"], "togri": 1, "izoh": "050-2020, band 5.2.3 — umumiy holda 155 mm, 18-9801 uchun 154 mm"},
      {"savol": "18-100 aravachasi, plankalar 10 mm, rama 2005-yilda tayyorlangan, depo ta'miri. «L₁» qancha?", "variantlar": ["642 mm dan kam emas", "648 (+2,0/−3,6) mm", "648 (+2,0/−6,6) mm", "648 (+1,6/−3,6) mm"], "togri": 1, "izoh": "050-2020, band 5.2.5 — 2001-yildan keyingi ramalar, ДР"},
      {"savol": "18-100, rama 1998-yilda tayyorlangan, kapital ta'mir. «L₁» qancha?", "variantlar": ["648 (+1,6/−3,6) mm", "648 (+2,0/−3,6) mm", "648 (+2,0/−6,6) mm", "648 (+1,6/−6,6) mm"], "togri": 3, "izoh": "050-2020, band 5.2.5 — 2001-yilgacha, КР"},
      {"savol": "18-100 modeli, plankalar orasida mahalliy zichmaslik 0,8 mm. Xulosa?", "variantlar": ["Yaroqli, me'yor 1 mm", "Aniqlab bo'lmaydi", "Yaroqli, cheklov yo'q", "Me'yordan chiqqan — 18-100 uchun 0,5 mm dan ko'p emas"], "togri": 3, "izoh": "050-2020, band 5.2.8"},
      {"savol": "Ikkita yon rama bazasi 2186 va 2189 mm chiqdi. Xulosa?", "variantlar": ["Ikkalasi ham brak", "Ikkalasi ham me'yorda, yig'sa bo'ladi", "Farq 3 mm — bunday juftlikni yig'ish mumkin emas", "Faqat ikkinchisi brak"], "togri": 2, "izoh": "Har biri 2185 (+7/−5) ichida, lekin farq 2 mm dan oshmasligi kerak"},
      {"savol": "18-9597 aravachasi. Prujina prutogining diametri qancha?", "variantlar": ["30/21 mm", "29/21 mm", "29/20 mm", "30/19 mm"], "togri": 0, "izoh": "050-2020, band 5.4.4"},
      {"savol": "18-100 modeli, ichki prujina 1985-yilda tayyorlangan. Prutok diametri?", "variantlar": ["19 mm", "30 mm", "20 mm", "21 mm"], "togri": 0, "izoh": "050-2020, band 5.4.4 — 1989-yilgacha 19 mm, 1989–2015 y. 21 mm"},
      {"savol": "18-100 modeli, prujina 2010-yilda tayyorlangan. Erkin holatdagi balandligi?", "variantlar": ["255 (+6/−3) mm", "249 (+7/−2) mm", "249 (+6/−2) mm", "249 (+6/−3) mm"], "togri": 1, "izoh": "050-2020, band 5.4.2 — 1989–2012 y."},
      {"savol": "Ponaning vertikal yeyilishi (tuzatmadan keyin) 1,8 mm, qiya yeyilishi 1,4 mm. Depo ta'miri. Xulosa?", "variantlar": ["Me'yordan chiqqan — umumiy 3,2 mm > 3 mm", "Yaroqli — umumiy 3,2 mm", "Aniqlab bo'lmaydi", "Yaroqli, bir tomondan 2 mm dan kichik"], "togri": 0, "izoh": "Umumiy yeyilish 3 mm dan oshmasligi kerak"},
      {"savol": "Ponaning vertikal yeyilishi 2,2 mm, qiya yeyilishi 0,5 mm. Umumiy 2,7 mm. Xulosa?", "variantlar": ["Me'yordan chiqqan — bir tomondan 2 mm dan oshgan", "Yaroqli", "Yaroqli — umumiy 3 mm dan kichik", "Naplavka qilinadi"], "togri": 0, "izoh": "Umumiy ≤3 mm bo'lsa ham, bir tomondan 2 mm dan oshmasligi shart"},
      {"savol": "Qiya yuzada 45° burchak dopuskini o'lchash uchun avval qaysi hujjatga qaraladi?", "variantlar": ["Faqat 050-2020", "050-2020 — o'lchash usuli, 052-2009 — me'yor va qaror", "Faqat 052-2009", "ПР НК В.3"], "togri": 1, "izoh": "Ikkala hujjat birga ishlaydi"},
      {"savol": "Ta'mirlangan aravachalar nazorati qachon o'tkaziladi va qayerga yoziladi?", "variantlar": ["Vagon ostiga podkatka qilingandan keyin, ВУ-32 jurnaliga", "Ta'mirdan darrov keyin, ВУ-32 jurnaliga", "Yozilmaydi", "Bo'yashdan keyin, ВУ-41 ga"], "togri": 0, "izoh": "052-2009, band 18.1"},
      {"savol": "Kapital ta'mirda nima albatta yangi o'rnatiladi?", "variantlar": ["Faqat shkvoren", "Tarkibiy friksion plankalar, cho'yan ponalar, yeyilishga chidamli prokladkalar, skolzun qalpoqlari", "Faqat prujinalar", "Hech nima"], "togri": 1, "izoh": "052-2009, band 18.6"},
      {"savol": "Depo ta'miridan chiqarishda podpyatnik tayanch yuzasi qancha moylanadi?", "variantlar": ["Moylanmaydi", "40…50 g", "150 g", "80 dan 100 grammgacha"], "togri": 3, "izoh": "052-2009, band 9.4 — grafit moyi yoki grafitli solidol"},
      {"savol": "С 03.04 loyihasi bo'yicha polimer prokladka o'rnatilganda podpyatnik moylanadimi?", "variantlar": ["Faqat kapital ta'mirda", "Yo'q, moylash taqiqlanadi", "Faqat qishda", "Ha, majburiy"], "togri": 1, "izoh": "052-2009, band 9.4"},
      {"savol": "Friksion plankalar qalinligi 16 mm bo'lsa nima qilinadi?", "variantlar": ["Texnik holatidan qat'i nazar tarkibiy plankalarga almashtiriladi", "O'z holicha qoldiriladi", "Faqat yeyilgani almashtiriladi", "Naplavka qilinadi"], "togri": 0, "izoh": "052-2009, band 8.14 — 10 mm + 6 mm yoki 8 mm + 8 mm"},
      {"savol": "Nadressor balkasida qiya tekislikning har qanday me'yordan ortiq yeyilishida qanday ta'mirga ruxsat beriladi?", "variantlar": ["Butun balka almashtiriladi", "№ 542 ПКБ ЦВ bo'yicha plastina-vstavkalarni payvandlash", "Brak", "Faqat naplavka"], "togri": 1, "izoh": "052-2009, band 9.5.3"},
      {"savol": "Yeyilishga chidamli prokladka «lapka»lari bukilgandan keyin siljish qancha bo'lishi mumkin?", "variantlar": ["Rama bo'ylab ±10 mm, ko'ndalangiga ±5 mm", "Siljimasligi kerak", "Cheklov yo'q", "±20 mm"], "togri": 0, "izoh": "052-2009, band 8.12"},
      {"savol": "Aravachalarga yeyilishga chidamli elementlar qanday o'rnatiladi?", "variantlar": ["Faqat bitta loyiha bo'yicha, aralash o'rnatish ruxsat etilmaydi", "Har xil loyihalarni aralashtirsa bo'ladi", "Ixtiyoriy", "Faqat kapital ta'mirda"], "togri": 0, "izoh": "052-2009, band 14.9"},
    ],
  },
];
